// Auto-generated learning aids for '2.12 (Newton in n Dimensions).
import type { GlossaryEntry, Flashcard } from '../components/widgets/decks'

export const NDNEWTON_GLOSSARY: GlossaryEntry[] = [
  {
    "term": {
      "en": "Nonlinear system $\\mathbf{f}(\\mathbf{x})=\\mathbf{0}$",
      "hu": "Nemlineáris rendszer $\\mathbf{f}(\\mathbf{x})=\\mathbf{0}$"
    },
    "def": {
      "en": "$n$ equations in $n$ unknowns, $\\mathbf{f}\\colon U\\subset\\mathbb{R}^n\\to\\mathbb{R}^n$. The vector generalization of the scalar root problem $f(x)=0$.",
      "hu": "$n$ egyenlet $n$ ismeretlenre, $\\mathbf{f}\\colon U\\subset\\mathbb{R}^n\\to\\mathbb{R}^n$. A skaláris $f(x)=0$ gyökfeladat vektoros általánosítása."
    }
  },
  {
    "term": {
      "en": "$n$-D Newton step (Eq. 2.30)",
      "hu": "$n$-D Newton-lépés (2.30)"
    },
    "def": {
      "en": "$\\mathbf{p}^{(k+1)}=\\mathbf{p}^{(k)}-\\big(\\mathbf{f}'(\\mathbf{p}^{(k)})\\big)^{-1}\\mathbf{f}(\\mathbf{p}^{(k)})$ — root of the linear approximation $\\mathbf{f}(\\mathbf{p}^{(k)})+\\mathbf{f}'(\\mathbf{p}^{(k)})(\\mathbf{x}-\\mathbf{p}^{(k)})$.",
      "hu": "$\\mathbf{p}^{(k+1)}=\\mathbf{p}^{(k)}-\\big(\\mathbf{f}'(\\mathbf{p}^{(k)})\\big)^{-1}\\mathbf{f}(\\mathbf{p}^{(k)})$ — az $\\mathbf{f}(\\mathbf{p}^{(k)})+\\mathbf{f}'(\\mathbf{p}^{(k)})(\\mathbf{x}-\\mathbf{p}^{(k)})$ lineáris közelítés gyöke."
    }
  },
  {
    "term": {
      "en": "Jacobian invertibility",
      "hu": "A Jacobi-mátrix invertálhatósága"
    },
    "def": {
      "en": "The step needs $\\mathbf{f}'(\\mathbf{p}^{(k)})$ nonsingular. Quadratic convergence is guaranteed when $\\mathbf{f}'(\\mathbf{p})$ is invertible at the root — the $n$-D analogue of $f'(p)\\ne0$.",
      "hu": "A lépéshez $\\mathbf{f}'(\\mathbf{p}^{(k)})$ nem szinguláris kell. A kvadratikus konvergencia akkor garantált, ha $\\mathbf{f}'(\\mathbf{p})$ a gyökben invertálható — az $f'(p)\\ne0$ $n$-D megfelelője."
    }
  },
  {
    "term": {
      "en": "Solve, don't invert ($\\mathbf{f}'\\mathbf{s}=-\\mathbf{f}$)",
      "hu": "Oldd meg, ne invertálj ($\\mathbf{f}'\\mathbf{s}=-\\mathbf{f}$)"
    },
    "def": {
      "en": "In practice set $\\mathbf{s}^{(k)}=\\mathbf{p}^{(k+1)}-\\mathbf{p}^{(k)}$ and solve the linear system $\\mathbf{f}'(\\mathbf{p}^{(k)})\\,\\mathbf{s}^{(k)}=-\\mathbf{f}(\\mathbf{p}^{(k)})$ (e.g. by LU), then $\\mathbf{p}^{(k+1)}=\\mathbf{p}^{(k)}+\\mathbf{s}^{(k)}$ — cheaper and more stable than forming the inverse.",
      "hu": "A gyakorlatban legyen $\\mathbf{s}^{(k)}=\\mathbf{p}^{(k+1)}-\\mathbf{p}^{(k)}$, és oldd meg az $\\mathbf{f}'(\\mathbf{p}^{(k)})\\,\\mathbf{s}^{(k)}=-\\mathbf{f}(\\mathbf{p}^{(k)})$ lineáris rendszert (pl. LU-val), majd $\\mathbf{p}^{(k+1)}=\\mathbf{p}^{(k)}+\\mathbf{s}^{(k)}$ — olcsóbb és stabilabb az inverz képzésénél."
    }
  },
  {
    "term": {
      "en": "Local quadratic convergence (Thm 2.56)",
      "hu": "Lokális kvadratikus konvergencia (2.56. tétel)"
    },
    "def": {
      "en": "If $\\mathbf{f}\\in C^2$, $\\mathbf{f}(\\mathbf{p})=\\mathbf{0}$ and $\\mathbf{f}'(\\mathbf{p})$ is invertible, the $n$-D Newton iteration converges locally and quadratically to $\\mathbf{p}$.",
      "hu": "Ha $\\mathbf{f}\\in C^2$, $\\mathbf{f}(\\mathbf{p})=\\mathbf{0}$ és $\\mathbf{f}'(\\mathbf{p})$ invertálható, az $n$-D Newton-iteráció lokálisan és kvadratikusan konvergál $\\mathbf{p}$-hez."
    }
  },
  {
    "term": {
      "en": "Why quadratic: $\\mathbf{g}'(\\mathbf{p})=\\mathbf{0}$",
      "hu": "Miért kvadratikus: $\\mathbf{g}'(\\mathbf{p})=\\mathbf{0}$"
    },
    "def": {
      "en": "Newton is the fixed-point map $\\mathbf{g}(\\mathbf{x})=\\mathbf{x}-(\\mathbf{f}'(\\mathbf{x}))^{-1}\\mathbf{f}(\\mathbf{x})$. Using $\\sum_j b_{ij}\\partial f_j/\\partial x_l=\\delta_{il}$ and $\\mathbf{f}(\\mathbf{p})=\\mathbf{0}$, every entry of the Jacobian $\\mathbf{g}'(\\mathbf{p})$ vanishes — the $n$-D version of $g'(p)=0$ (Thm 2.55).",
      "hu": "Newton a $\\mathbf{g}(\\mathbf{x})=\\mathbf{x}-(\\mathbf{f}'(\\mathbf{x}))^{-1}\\mathbf{f}(\\mathbf{x})$ fixpont-leképezés. A $\\sum_j b_{ij}\\partial f_j/\\partial x_l=\\delta_{il}$ és $\\mathbf{f}(\\mathbf{p})=\\mathbf{0}$ felhasználásával a $\\mathbf{g}'(\\mathbf{p})$ Jacobi-mátrix minden eleme eltűnik — a $g'(p)=0$ $n$-D változata (2.55. tétel)."
    }
  },
  {
    "term": {
      "en": "Newton increment $\\mathbf{s}^{(k)}$",
      "hu": "Newton-növekmény $\\mathbf{s}^{(k)}$"
    },
    "def": {
      "en": "$\\mathbf{s}^{(k)}=\\mathbf{p}^{(k+1)}-\\mathbf{p}^{(k)}$, the solution of $\\mathbf{f}'\\mathbf{s}=-\\mathbf{f}$. Its norm $\\|\\mathbf{s}^{(k)}\\|$ is the natural absolute-step stopping quantity.",
      "hu": "$\\mathbf{s}^{(k)}=\\mathbf{p}^{(k+1)}-\\mathbf{p}^{(k)}$, az $\\mathbf{f}'\\mathbf{s}=-\\mathbf{f}$ megoldása. Normája $\\|\\mathbf{s}^{(k)}\\|$ a természetes abszolút-lépés megállási mennyiség."
    }
  },
  {
    "term": {
      "en": "Cost per step",
      "hu": "Lépésenkénti költség"
    },
    "def": {
      "en": "Each step evaluates $\\mathbf{f}$ and the full $n\\times n$ Jacobian, then solves an $n\\times n$ linear system ($O(n^3)$). The expense of recomputing/factoring $\\mathbf{f}'$ every step motivates quasi-Newton (Broyden).",
      "hu": "Minden lépés kiértékeli $\\mathbf{f}$-et és a teljes $n\\times n$ Jacobi-mátrixot, majd megold egy $n\\times n$ lineáris rendszert ($O(n^3)$). A $\\mathbf{f}'$ lépésenkénti újraszámítása/faktorizálása drága — ez motiválja a kvázi-Newton (Broyden) módszert."
    }
  }
]

export const NDNEWTON_FLASHCARDS: Flashcard[] = [
  {"q":{"en":"In $n$ dimensions, what equation defines a vector $\\mathbf{p}$ as a fixed point of the function $\\mathbf{g}$?","hu":"$n$ dimenzióban melyik egyenlet definiál egy $\\mathbf{p}$ vektort a $\\mathbf{g}$ függvény fixpontjaként?"},"a":{"en":"$\\mathbf{p} = \\mathbf{g}(\\mathbf{p})$","hu":"$\\mathbf{p} = \\mathbf{g}(\\mathbf{p})$"}},
  {"q":{"en":"What is the recursive formula for the fixed-point iteration to approximate a solution to $\\mathbf{x} = \\mathbf{g}(\\mathbf{x})$?","hu":"Mi a fixpont-iteráció rekurzív képlete a $\\mathbf{x} = \\mathbf{g}(\\mathbf{x})$ megoldásának közelítésére?"},"a":{"en":"$\\mathbf{p}^{(k+1)} = \\mathbf{g}(\\mathbf{p}^{(k)})$","hu":"$\\mathbf{p}^{(k+1)} = \\mathbf{g}(\\mathbf{p}^{(k)})$"}},
  {"q":{"en":"A function $\\mathbf{g}\\colon E \\to \\mathbb{R}^n$ is a contraction on $E$ if there exists a constant $c$ such that $0 \\leq c < 1$ and _____.","hu":"Egy $\\mathbf{g}\\colon E \\to \\mathbb{R}^n$ függvény kontrakció $E$-n, ha létezik olyan $c$ konstans, hogy $0 \\leq c < 1$ és _____."},"a":{"en":"$\\|\\mathbf{g}(\\mathbf{x}) - \\mathbf{g}(\\mathbf{y})\\| \\leq c\\|\\mathbf{x} - \\mathbf{y}\\|$ for all $\\mathbf{x}, \\mathbf{y} \\in E$","hu":"$\\|\\mathbf{g}(\\mathbf{x}) - \\mathbf{g}(\\mathbf{y})\\| \\leq c\\|\\mathbf{x} - \\mathbf{y}\\|$ minden $\\mathbf{x}, \\mathbf{y} \\in E$-re"}},
  {"q":{"en":"What type of set must $E \\subset \\mathbb{R}^n$ be for the global fixed-point theorem to guarantee convergence of $\\mathbf{p}^{(k+1)} = \\mathbf{g}(\\mathbf{p}^{(k)})$?","hu":"Milyen típusú halmaznak kell lennie $E \\subset \\mathbb{R}^n$-nek, hogy a globális fixponttétel garantálja a $\\mathbf{p}^{(k+1)} = \\mathbf{g}(\\mathbf{p}^{(k)})$ konvergenciáját?"},"a":{"en":"A closed set.","hu":"Zárt halmaznak."}},
  {"q":{"en":"To apply the fixed-point theorem on a set $E$, the function $\\mathbf{g}$ must map $E$ to _____.","hu":"A fixponttétel egy $E$ halmazon való alkalmazásához a $\\mathbf{g}$ függvénynek $E$-t _____ kell leképeznie."},"a":{"en":"The set $E$ itself ($\\mathbf{g}\\colon E \\to E$).","hu":"Magába az $E$ halmazba ($\\mathbf{g}\\colon E \\to E$)."}},
  {"q":{"en":"According to the fixed-point theorem, if $\\mathbf{g}$ is a contraction on a closed set $E$ and $\\mathbf{g}\\colon E \\to E$, how many fixed points does $\\mathbf{g}$ have in $E$?","hu":"A fixponttétel szerint, ha $\\mathbf{g}$ kontrakció egy $E$ zárt halmazon és $\\mathbf{g}\\colon E \\to E$, hány fixpontja van $\\mathbf{g}$-nek $E$-ben?"},"a":{"en":"Exactly one (a unique fixed point).","hu":"Pontosan egy (egyértelmű fixpont)."}},
  {"q":{"en":"What is the minimum order of convergence guaranteed by the general contraction mapping theorem for fixed-point iteration?","hu":"Mi a fixpont-iterációra az általános kontrakciós tétel által garantált minimális konvergenciarend?"},"a":{"en":"Linear convergence.","hu":"Lineáris konvergencia."}},
  {"q":{"en":"In the proof of the fixed-point theorem, what sequence property is used to demonstrate that the iterates $\\mathbf{p}^{(k)}$ converge to a limit?","hu":"A fixponttétel bizonyításában milyen sorozattulajdonsággal mutatjuk meg, hogy a $\\mathbf{p}^{(k)}$ közelítések egy határértékhez konvergálnak?"},"a":{"en":"The iterates form a Cauchy sequence.","hu":"A közelítések Cauchy-sorozatot alkotnak."}},
  {"q":{"en":"How is the constant $c$ in the contraction definition related to the Lipschitz property?","hu":"Hogyan kapcsolódik a kontrakció definíciójában szereplő $c$ konstans a Lipschitz-tulajdonsághoz?"},"a":{"en":"$c$ is the Lipschitz constant of the function $\\mathbf{g}$ on $E$.","hu":"$c$ a $\\mathbf{g}$ függvény Lipschitz-konstansa $E$-n."}},
  {"q":{"en":"Which mathematical identity is used to bound the distance $\\|\\mathbf{p}^{(k)} - \\mathbf{p}^{(m)}\\|$ in the fixed-point theorem proof?","hu":"Melyik matematikai azonossággal korlátozzuk a $\\|\\mathbf{p}^{(k)} - \\mathbf{p}^{(m)}\\|$ távolságot a fixponttétel bizonyításában?"},"a":{"en":"The triangle inequality.","hu":"A háromszög-egyenlőtlenséggel."}},
  {"q":{"en":"In the proof of convergence, what formula represents the upper bound of the sum of the norms of differences using the contraction constant $c$ and the first step $\\|\\mathbf{p}^{(1)} - \\mathbf{p}^{(0)}\\|$?","hu":"A konvergencia bizonyításában melyik képlet adja a különbségek normáinak összegére a felső korlátot a $c$ kontrakciós konstanssal és az első lépéssel $\\|\\mathbf{p}^{(1)} - \\mathbf{p}^{(0)}\\|$?"},"a":{"en":"$c^m \\sum_{i=0}^\\infty c^i \\|\\mathbf{p}^{(1)} - \\mathbf{p}^{(0)}\\|$","hu":"$c^m \\sum_{i=0}^\\infty c^i \\|\\mathbf{p}^{(1)} - \\mathbf{p}^{(0)}\\|$"}},
  {"q":{"en":"What property of $\\mathbf{g}$ is invoked to show that $\\mathbf{g}(\\mathbf{p}^{(k)}) \\to \\mathbf{g}(\\mathbf{p})$ as $\\mathbf{p}^{(k)} \\to \\mathbf{p}$?","hu":"A $\\mathbf{g}$ melyik tulajdonságára hivatkozunk annak megmutatására, hogy $\\mathbf{g}(\\mathbf{p}^{(k)}) \\to \\mathbf{g}(\\mathbf{p})$, ha $\\mathbf{p}^{(k)} \\to \\mathbf{p}$?"},"a":{"en":"The continuity of the function $\\mathbf{g}$.","hu":"A $\\mathbf{g}$ függvény folytonosságára."}},
  {"q":{"en":"How is the uniqueness of the fixed point $\\mathbf{p}$ proven using the contraction property?","hu":"Hogyan bizonyítjuk a $\\mathbf{p}$ fixpont egyértelműségét a kontrakciós tulajdonsággal?"},"a":{"en":"By showing $\\|\\mathbf{p} - \\bar{\\mathbf{p}}\\| \\leq c\\|\\mathbf{p} - \\bar{\\mathbf{p}}\\|$, which implies the distance must be zero since $c < 1$.","hu":"Megmutatva, hogy $\\|\\mathbf{p} - \\bar{\\mathbf{p}}\\| \\leq c\\|\\mathbf{p} - \\bar{\\mathbf{p}}\\|$, ami $c < 1$ miatt azt jelenti, hogy a távolság nulla."}},
  {"q":{"en":"For local convergence at a fixed point $\\mathbf{p}$, what condition must the matrix norm of the Jacobian $\\mathbf{g}'(\\mathbf{p})$ satisfy?","hu":"A $\\mathbf{p}$ fixpontbeli lokális konvergenciához milyen feltételt kell teljesítenie a $\\mathbf{g}'(\\mathbf{p})$ Jacobi-mátrix normájának?"},"a":{"en":"$\\|\\mathbf{g}'(\\mathbf{p})\\| < 1$","hu":"$\\|\\mathbf{g}'(\\mathbf{p})\\| < 1$"}},
  {"q":{"en":"When checking for local convergence, what type of norm must be used for the Jacobian matrix $\\mathbf{g}'(\\mathbf{p})$?","hu":"A lokális konvergencia ellenőrzésekor milyen típusú normát kell használni a $\\mathbf{g}'(\\mathbf{p})$ Jacobi-mátrixra?"},"a":{"en":"A matrix norm generated by a vector norm.","hu":"Egy vektornorma által generált mátrixnormát."}},
  {"q":{"en":"To guarantee local convergence via the Jacobian matrix norm condition, what differentiability class must $\\mathbf{g}$ belong to on an open set $E$?","hu":"A Jacobi-mátrixnorma feltétel útján való lokális konvergencia garantálásához milyen differenciálhatósági osztályba kell tartoznia $\\mathbf{g}$-nek egy $E$ nyílt halmazon?"},"a":{"en":"$C^1$ (continuously differentiable).","hu":"$C^1$ (folytonosan differenciálható)."}},
  {"q":{"en":"Which theorem is used in the local convergence proof to link the function values to the Jacobian matrix?","hu":"Melyik tételt használjuk a lokális konvergencia bizonyításában a függvényértékek és a Jacobi-mátrix összekapcsolására?"},"a":{"en":"Lagrange's Mean Value Theorem.","hu":"A Lagrange-féle középértéktételt."}},
  {"q":{"en":"In the local convergence proof, how is the neighborhood $V$ defined around the fixed point $\\mathbf{p}$?","hu":"A lokális konvergencia bizonyításában hogyan definiáljuk a $\\mathbf{p}$ fixpont körüli $V$ környezetet?"},"a":{"en":"$V = \\{\\mathbf{x}\\colon \\|\\mathbf{x} - \\mathbf{p}\\| \\leq \\delta\\}$ where $\\|\\mathbf{g}'(\\mathbf{x})\\| \\leq c < 1$.","hu":"$V = \\{\\mathbf{x}\\colon \\|\\mathbf{x} - \\mathbf{p}\\| \\leq \\delta\\}$, ahol $\\|\\mathbf{g}'(\\mathbf{x})\\| \\leq c < 1$."}},
  {"q":{"en":"If $\\mathbf{g}(x_1, x_2) = \\begin{pmatrix} g_1(x_1, x_2) \\\\ g_2(x_1, x_2) \\end{pmatrix}$, what is the entry in the first row and second column of the Jacobian matrix $\\mathbf{g}'(\\mathbf{x})$?","hu":"Ha $\\mathbf{g}(x_1, x_2) = \\begin{pmatrix} g_1(x_1, x_2) \\\\ g_2(x_1, x_2) \\end{pmatrix}$, mi a $\\mathbf{g}'(\\mathbf{x})$ Jacobi-mátrix első sorának, második oszlopának eleme?"},"a":{"en":"$\\frac{\\partial g_1}{\\partial x_2}$","hu":"$\\frac{\\partial g_1}{\\partial x_2}$"}},
  {"q":{"en":"Term: Jacobian Matrix","hu":"Fogalom: Jacobi-mátrix"},"a":{"en":"Definition: A matrix of all first-order partial derivatives of a vector-valued function.","hu":"Definíció: Egy vektorértékű függvény összes elsőrendű parciális deriváltjának mátrixa."}},
  {"q":{"en":"In the provided example, $\\mathbf{g}'(1, 0) = \\begin{pmatrix} 0 & \\frac{1}{4} \\\\ \\frac{1}{3} & 0 \\end{pmatrix}$. What is the 1-norm ($\\|\\cdot\\|_1$) of this matrix?","hu":"A megadott példában $\\mathbf{g}'(1, 0) = \\begin{pmatrix} 0 & \\frac{1}{4} \\\\ \\frac{1}{3} & 0 \\end{pmatrix}$. Mi e mátrix 1-normája ($\\|\\cdot\\|_1$)?"},"a":{"en":"$\\frac{1}{3}$","hu":"$\\frac{1}{3}$"}},
  {"q":{"en":"Based on $\\|\\mathbf{g}'(1, 0)\\|_1 = \\frac{1}{3}$, what can be concluded about the fixed-point iteration near $(1, 0)^T$?","hu":"A $\\|\\mathbf{g}'(1, 0)\\|_1 = \\frac{1}{3}$ alapján mit következtethetünk a fixpont-iterációról a $(1, 0)^T$ közelében?"},"a":{"en":"It is locally convergent.","hu":"Lokálisan konvergens."}},
  {"q":{"en":"What specific condition on the Jacobian matrix $\\mathbf{g}'(\\mathbf{p})$ leads to quadratic local convergence?","hu":"Milyen konkrét feltétel a $\\mathbf{g}'(\\mathbf{p})$ Jacobi-mátrixra vezet kvadratikus lokális konvergenciához?"},"a":{"en":"$\\mathbf{g}'(\\mathbf{p}) = \\mathbf{0}$ (the zero matrix).","hu":"$\\mathbf{g}'(\\mathbf{p}) = \\mathbf{0}$ (a nullmátrix)."}},
  {"q":{"en":"To achieve quadratic convergence, what is the required differentiability class for function $\\mathbf{g}$?","hu":"A kvadratikus konvergencia eléréséhez milyen differenciálhatósági osztály kell a $\\mathbf{g}$ függvényre?"},"a":{"en":"$C^2$ (twice continuously differentiable).","hu":"$C^2$ (kétszer folytonosan differenciálható)."}},
  {"q":{"en":"Which expansion technique is used to prove the quadratic convergence of fixed-point iteration when $\\mathbf{g}'(\\mathbf{p}) = \\mathbf{0}$?","hu":"Milyen kifejtési technikával bizonyítjuk a fixpont-iteráció kvadratikus konvergenciáját, amikor $\\mathbf{g}'(\\mathbf{p}) = \\mathbf{0}$?"},"a":{"en":"Second-order Taylor approximation.","hu":"Másodrendű Taylor-közelítéssel."}},
  {"q":{"en":"The error bound for quadratic convergence is given by $\\|\\mathbf{p}^{(k+1)} - \\mathbf{p}\\|_\\infty \\leq c \\|\\mathbf{p}^{(k)} - \\mathbf{p}\\|_\\infty^2$. What is the constant $c$ proportional to in the proof?","hu":"A kvadratikus konvergencia hibakorlátja $\\|\\mathbf{p}^{(k+1)} - \\mathbf{p}\\|_\\infty \\leq c \\|\\mathbf{p}^{(k)} - \\mathbf{p}\\|_\\infty^2$. Mivel arányos a $c$ konstans a bizonyításban?"},"a":{"en":"$\\frac{n^2}{2} M$, where $M$ is a bound on the second partial derivatives.","hu":"$\\frac{n^2}{2} M$-mel, ahol $M$ a második parciális deriváltak korlátja."}},
  {"q":{"en":"True or False: If $\\mathbf{g}'(\\mathbf{p}) = \\mathbf{0}$, the fixed-point iteration is guaranteed to converge for any initial value in $\\mathbb{R}^n$.","hu":"Igaz vagy hamis: Ha $\\mathbf{g}'(\\mathbf{p}) = \\mathbf{0}$, a fixpont-iteráció garantáltan konvergál bármely $\\mathbb{R}^n$-beli kezdőértékre."},"a":{"en":"False; it only guarantees local convergence within some distance $\\delta$.","hu":"Hamis; csak lokális konvergenciát garantál egy bizonyos $\\delta$ távolságon belül."}},
  {"q":{"en":"How is the Jacobian entry $\\frac{\\partial}{\\partial x_1} [\\frac{1}{4}(e^{x_1 x_2} + 3)]$ calculated?","hu":"Hogyan számoljuk a $\\frac{\\partial}{\\partial x_1} [\\frac{1}{4}(e^{x_1 x_2} + 3)]$ Jacobi-elemet?"},"a":{"en":"Using the chain rule, it is $\\frac{1}{4} x_2 e^{x_1 x_2}$.","hu":"A láncszabállyal: $\\frac{1}{4} x_2 e^{x_1 x_2}$."}},
  {"q":{"en":"How is the Jacobian entry $\\frac{\\partial}{\\partial x_2} [\\frac{1}{3}(x_1 - x_2^2 - 1)]$ calculated?","hu":"Hogyan számoljuk a $\\frac{\\partial}{\\partial x_2} [\\frac{1}{3}(x_1 - x_2^2 - 1)]$ Jacobi-elemet?"},"a":{"en":"The derivative of the constant $x_1-1$ is 0, and the derivative of $-x_2^2$ is $-2x_2$, resulting in $-\\frac{2}{3}x_2$.","hu":"Az $x_1-1$ konstans deriváltja 0, a $-x_2^2$ deriváltja $-2x_2$, így az eredmény $-\\frac{2}{3}x_2$."}},
  {"q":{"en":"If the Jacobian matrix at the fixed point is $\\mathbf{0}$, what term in the Taylor expansion of $g_i$ around $\\mathbf{p}$ becomes zero besides $g_i(\\mathbf{p}) - p_i$?","hu":"Ha a fixpontbeli Jacobi-mátrix $\\mathbf{0}$, a $g_i$ $\\mathbf{p}$ körüli Taylor-kifejtésében a $g_i(\\mathbf{p}) - p_i$-n kívül melyik tag lesz nulla?"},"a":{"en":"The summation containing the first-order partial derivatives: $\\sum_{j=1}^n \\frac{\\partial g_i(\\mathbf{p})}{\\partial x_j}(x_j - p_j)$.","hu":"Az elsőrendű parciális deriváltakat tartalmazó összeg: $\\sum_{j=1}^n \\frac{\\partial g_i(\\mathbf{p})}{\\partial x_j}(x_j - p_j)$."}},
  {"q":{"en":"What is the relationship between the order of convergence and the number of derivatives of $\\mathbf{g}$ that vanish at the fixed point?","hu":"Mi a kapcsolat a konvergenciarend és a fixpontban eltűnő $\\mathbf{g}$-deriváltak száma között?"},"a":{"en":"If the first derivative vanishes ($\\mathbf{g}'(\\mathbf{p}) = \\mathbf{0}$), the order is at least quadratic ($2^{nd}$ order).","hu":"Ha az első derivált eltűnik ($\\mathbf{g}'(\\mathbf{p}) = \\mathbf{0}$), a rend legalább kvadratikus (2. rendű)."}},
  {"q":{"en":"In the example provided, what were the exact solutions $(x_1, x_2)$ for the system $4x_1 - e^{x_1 x_2} - 3 = 0$ and $x_1 - x_2^2 - 3x_2 - 1 = 0$?","hu":"A megadott példában mik voltak a $4x_1 - e^{x_1 x_2} - 3 = 0$ és $x_1 - x_2^2 - 3x_2 - 1 = 0$ rendszer pontos $(x_1, x_2)$ megoldásai?"},"a":{"en":"$x_1 = 1$ and $x_2 = 0$.","hu":"$x_1 = 1$ és $x_2 = 0$."}},
  {"q":{"en":"For the system $\\mathbf{x} = \\mathbf{g}(\\mathbf{x})$, the sequence $\\mathbf{p}^{(k)}$ converges to $\\mathbf{p}$ if $\\mathbf{g}$ is a contraction. What does $c$ represent in the error estimate $\\|\\mathbf{p}^{(k+1)} - \\mathbf{p}\\| \\leq c \\|\\mathbf{p}^{(k)} - \\mathbf{p}\\|$?","hu":"A $\\mathbf{x} = \\mathbf{g}(\\mathbf{x})$ rendszerre a $\\mathbf{p}^{(k)}$ sorozat $\\mathbf{p}$-hez konvergál, ha $\\mathbf{g}$ kontrakció. Mit jelöl $c$ a $\\|\\mathbf{p}^{(k+1)} - \\mathbf{p}\\| \\leq c \\|\\mathbf{p}^{(k)} - \\mathbf{p}\\|$ hibabecslésben?"},"a":{"en":"The asymptotic error constant (or contraction factor).","hu":"Az aszimptotikus hibakonstanst (kontrakciós tényezőt)."}},
  {"q":{"en":"If a fixed-point iteration converges quadratically, how does the number of correct digits roughly change with each iteration?","hu":"Ha egy fixpont-iteráció kvadratikusan konvergál, hogyan változik nagyjából a helyes jegyek száma iterációnként?"},"a":{"en":"The number of correct digits approximately doubles.","hu":"A helyes jegyek száma körülbelül megduplázódik."}},
  {"q":{"en":"Why is the assumption that $E$ is an open set necessary for the local convergence theorem involving the Jacobian?","hu":"Miért szükséges az a feltevés, hogy $E$ nyílt halmaz, a Jacobi-mátrixot érintő lokális konvergenciatételhez?"},"a":{"en":"To ensure that a neighborhood (ball) around the fixed point exists entirely within the domain $E$.","hu":"Hogy biztosítsuk: a fixpont körüli környezet (gömb) teljesen az $E$ tartományon belül van."}},
  {"q":{"en":"In the context of the Taylor expansion proof, what does the symbol $\\xi$ represent?","hu":"A Taylor-kifejtéses bizonyítás kontextusában mit jelöl a $\\xi$ szimbólum?"},"a":{"en":"A point on the line segment between $\\mathbf{x}$ and $\\mathbf{p}$ where the derivative is evaluated.","hu":"Egy pontot az $\\mathbf{x}$ és $\\mathbf{p}$ közötti szakaszon, ahol a deriváltat kiértékeljük."}},
  {"q":{"en":"Cloze: The fixed-point theorem ensures that for a contraction mapping on a closed set, the iteration converges for _____ initial value $\\mathbf{p}^{(0)} \\in E$.","hu":"Kiegészítés: A fixponttétel biztosítja, hogy egy zárt halmazon vett kontrakció esetén az iteráció _____ $\\mathbf{p}^{(0)} \\in E$ kezdőértékre konvergál."},"a":{"en":"any","hu":"bármely"}},
  {"q":{"en":"Concept: Local Quadratic Convergence","hu":"Fogalom: Lokális kvadratikus konvergencia"},"a":{"en":"Condition: $\\mathbf{g}(\\mathbf{p}) = \\mathbf{p}$, $\\mathbf{g}'(\\mathbf{p}) = \\mathbf{0}$, and $\\mathbf{g} \\in C^2$.","hu":"Feltétel: $\\mathbf{g}(\\mathbf{p}) = \\mathbf{p}$, $\\mathbf{g}'(\\mathbf{p}) = \\mathbf{0}$ és $\\mathbf{g} \\in C^2$."}},
  {"q":{"en":"Formula: $\\|\\mathbf{A}\\|_1$ (for a matrix $\\mathbf{A}$)","hu":"Képlet: $\\|\\mathbf{A}\\|_1$ (egy $\\mathbf{A}$ mátrixra)"},"a":{"en":"The maximum absolute column sum of the matrix.","hu":"A mátrix maximális abszolút oszlopösszege."}},
  {"q":{"en":"What is the result of $\\|\\mathbf{g}'(1,0)\\|_\\infty$ for $\\mathbf{g}'(1,0) = \\begin{pmatrix} 0 & 1/4 \\\\ 1/3 & 0 \\end{pmatrix}$?","hu":"Mi a $\\|\\mathbf{g}'(1,0)\\|_\\infty$ eredménye a $\\mathbf{g}'(1,0) = \\begin{pmatrix} 0 & 1/4 \\\\ 1/3 & 0 \\end{pmatrix}$-ra?"},"a":{"en":"$1/3$","hu":"$1/3$"}},
  {"q":{"en":"If $\\|\\mathbf{g}'(\\mathbf{p})\\| = 0.5$, what is the asymptotic rate of convergence for the fixed-point iteration?","hu":"Ha $\\|\\mathbf{g}'(\\mathbf{p})\\| = 0.5$, mi a fixpont-iteráció aszimptotikus konvergenciasebessége?"},"a":{"en":"Linear convergence with a rate of $0.5$.","hu":"Lineáris konvergencia $0.5$ ütemmel."}},
  {"q":{"en":"In $n$ dimensions, if $\\mathbf{g}'(\\mathbf{p})$ is the zero matrix, the iteration is locally _____ convergent.","hu":"$n$ dimenzióban, ha $\\mathbf{g}'(\\mathbf{p})$ a nullmátrix, az iteráció lokálisan _____ konvergens."},"a":{"en":"quadratically (or second-order)","hu":"kvadratikusan (másodrendűen)"}},
  {"q":{"en":"How is the term $p_i^{(k+1)} - p_i$ expressed in the quadratic convergence proof using second derivatives?","hu":"Hogyan fejezzük ki a $p_i^{(k+1)} - p_i$ tagot a kvadratikus konvergencia bizonyításában a második deriváltakkal?"},"a":{"en":"$p_i^{(k+1)} - p_i = \\frac{1}{2} \\sum_{j=1}^n \\sum_{l=1}^n \\frac{\\partial^2 g_i(\\xi)}{\\partial x_j \\partial x_l} (p_j^{(k)} - p_j)(p_l^{(k)} - p_l)$","hu":"$p_i^{(k+1)} - p_i = \\frac{1}{2} \\sum_{j=1}^n \\sum_{l=1}^n \\frac{\\partial^2 g_i(\\xi)}{\\partial x_j \\partial x_l} (p_j^{(k)} - p_j)(p_l^{(k)} - p_l)$"}},
  {"q":{"en":"The fixed-point iteration $\\mathbf{p}^{(k+1)} = \\mathbf{g}(\\mathbf{p}^{(k)})$ is essentially a functional iteration in _____.","hu":"A $\\mathbf{p}^{(k+1)} = \\mathbf{g}(\\mathbf{p}^{(k)})$ fixpont-iteráció lényegében egy függvény-iteráció _____."},"a":{"en":"Multidimensional space (or $\\mathbb{R}^n$).","hu":"Többdimenziós térben ($\\mathbb{R}^n$-ben)."}},
  {"q":{"en":"Why is the condition $c < 1$ critical for a contraction?","hu":"Miért kritikus a $c < 1$ feltétel egy kontrakciónál?"},"a":{"en":"It ensures that the distance between points strictly decreases after applying the function.","hu":"Biztosítja, hogy a pontok közötti távolság szigorúan csökken a függvény alkalmazása után."}},
  {"q":{"en":"What happens to the fixed-point iteration if $\\|\\mathbf{g}'(\\mathbf{p})\\| > 1$?","hu":"Mi történik a fixpont-iterációval, ha $\\|\\mathbf{g}'(\\mathbf{p})\\| > 1$?"},"a":{"en":"The iteration will generally diverge from the fixed point $\\mathbf{p}$.","hu":"Az iteráció általában eltávolodik a $\\mathbf{p}$ fixponttól (divergál)."}},
  {"q":{"en":"Which component of the error vector $\\mathbf{p}^{(k)} - \\mathbf{p}$ determines the $\\|\\cdot\\|_\\infty$ norm?","hu":"A $\\mathbf{p}^{(k)} - \\mathbf{p}$ hibavektor melyik komponense határozza meg a $\\|\\cdot\\|_\\infty$ normát?"},"a":{"en":"The component with the largest absolute value.","hu":"A legnagyobb abszolút értékű komponens."}},
  {"q":{"en":"In the example iteration table, starting from $(-2, -2)^T$, which iteration $k$ first shows $p_1^{(k)}$ and $p_2^{(k)}$ both within $0.1$ of the solution $(1, 0)^T$?","hu":"A példa iterációs táblájában, $(-2, -2)^T$-ből indulva, melyik $k$ iterációnál van először $p_1^{(k)}$ és $p_2^{(k)}$ is a $(1, 0)^T$ megoldás $0.1$-es környezetében?"},"a":{"en":"$k = 7$ ($p_1 \\approx 0.949$, $p_2 \\approx -0.061$).","hu":"$k = 7$ ($p_1 \\approx 0.949$, $p_2 \\approx -0.061$)."}},
  {"q":{"en":"In the system $x_1 = g_1(x_1, x_2)$, if $g_1$ is a constant, what is the value of $\\frac{\\partial g_1}{\\partial x_1}$?","hu":"Az $x_1 = g_1(x_1, x_2)$ rendszerben, ha $g_1$ konstans, mennyi $\\frac{\\partial g_1}{\\partial x_1}$ értéke?"},"a":{"en":"0","hu":"0"}},
  {"q":{"en":"Cloze: If a function $\\mathbf{g}$ satisfies the conditions for the fixed-point theorem, the error $\\|\\mathbf{p}^{(k)} - \\mathbf{p}\\|$ is bounded by a _____ series.","hu":"Kiegészítés: Ha egy $\\mathbf{g}$ függvény teljesíti a fixponttétel feltételeit, a $\\|\\mathbf{p}^{(k)} - \\mathbf{p}\\|$ hibát egy _____ sor korlátozza."},"a":{"en":"geometric","hu":"mértani (geometriai)"}},
  {"q":{"en":"How many iterations did the example take to reach a precision where $p_2$ is approximately $-0.0001$?","hu":"Hány iterációba telt a példában elérni azt a pontosságot, ahol $p_2$ körülbelül $-0.0001$?"},"a":{"en":"12 iterations.","hu":"12 iteráció."}},
  {"q":{"en":"What is the Jacobian matrix of $\\mathbf{g}(\\mathbf{x}) = \\mathbf{A}\\mathbf{x} + \\mathbf{b}$?","hu":"Mi a $\\mathbf{g}(\\mathbf{x}) = \\mathbf{A}\\mathbf{x} + \\mathbf{b}$ Jacobi-mátrixa?"},"a":{"en":"The matrix $\\mathbf{A}$.","hu":"Az $\\mathbf{A}$ mátrix."}},
  {"q":{"en":"In the case of a linear system $\\mathbf{x} = \\mathbf{A}\\mathbf{x} + \\mathbf{b}$, what is the condition for global convergence of the fixed-point iteration?","hu":"Egy $\\mathbf{x} = \\mathbf{A}\\mathbf{x} + \\mathbf{b}$ lineáris rendszer esetén mi a fixpont-iteráció globális konvergenciájának feltétele?"},"a":{"en":"The matrix norm $\\|\\mathbf{A}\\|$ must be less than 1.","hu":"A $\\|\\mathbf{A}\\|$ mátrixnormának 1-nél kisebbnek kell lennie."}},
  {"q":{"en":"What does $C^1$ notation imply about the partial derivatives of a function?","hu":"Mit jelent a $C^1$ jelölés egy függvény parciális deriváltjaira nézve?"},"a":{"en":"They all exist and are continuous functions.","hu":"Mind léteznek és folytonos függvények."}},
  {"q":{"en":"If the fixed-point iteration converges such that the error $\\|e_{k+1}\\| \\approx C \\|e_k\\|^2$, what is the order of convergence?","hu":"Ha a fixpont-iteráció úgy konvergál, hogy a hiba $\\|e_{k+1}\\| \\approx C \\|e_k\\|^2$, mi a konvergenciarend?"},"a":{"en":"Second-order (Quadratic).","hu":"Másodrendű (kvadratikus)."}},
  {"q":{"en":"Under what circumstance does the fixed-point theorem guarantee that the unique fixed point is actually reached in a finite number of steps?","hu":"Milyen körülmények között garantálja a fixponttétel, hogy az egyértelmű fixpontot ténylegesen véges számú lépésben elérjük?"},"a":{"en":"Only if the starting point $\\mathbf{p}^{(0)}$ is already the fixed point or $\\mathbf{g}$ is a constant map.","hu":"Csak ha a $\\mathbf{p}^{(0)}$ kezdőpont már maga a fixpont, vagy $\\mathbf{g}$ konstans leképezés."}},
  {"q":{"en":"What is the 'Lipschitz constant' in the context of the contraction mapping theorem?","hu":"Mi a „Lipschitz-konstans” a kontrakciós leképezési tétel kontextusában?"},"a":{"en":"The constant $c \\in [0, 1)$ that bounds the ratio of distances between images and arguments.","hu":"Az a $c \\in [0, 1)$ konstans, amely korlátozza a képek és az argumentumok közötti távolságok arányát."}},
  {"q":{"en":"True or False: The choice of norm $(\\|\\cdot\\|_1, \\|\\cdot\\|_2, \\|\\cdot\\|_\\infty)$ can determine whether a mapping is considered a contraction.","hu":"Igaz vagy hamis: A norma választása $(\\|\\cdot\\|_1, \\|\\cdot\\|_2, \\|\\cdot\\|_\\infty)$ eldöntheti, hogy egy leképezés kontrakciónak számít-e."},"a":{"en":"True; a function may be a contraction in one norm but not in another.","hu":"Igaz; egy függvény az egyik normában kontrakció lehet, a másikban nem."}},
  {"q":{"en":"What is the Jacobian of the specific function $g_2(x_1, x_2) = \\frac{1}{3}(x_1 - x_2^2 - 1)$ evaluated at $(1, 0)$?","hu":"Mi a $g_2(x_1, x_2) = \\frac{1}{3}(x_1 - x_2^2 - 1)$ függvény Jacobi-ja $(1, 0)$-ban kiértékelve?"},"a":{"en":"$(\\frac{1}{3}, 0)$","hu":"$(\\frac{1}{3}, 0)$"}},
  {"q":{"en":"Why is the fixed-point iteration useful for nonlinear systems of equations?","hu":"Miért hasznos a fixpont-iteráció nemlineáris egyenletrendszerekhez?"},"a":{"en":"It provides a simple numerical procedure to approximate solutions without requiring complex matrix inversions in every step.","hu":"Egyszerű numerikus eljárást ad megoldások közelítésére anélkül, hogy minden lépésben bonyolult mátrixinvertálásra lenne szükség."}}
]
