// Auto-generated learning aids for '2.10 (Vector and Matrix Norms).
import type { GlossaryEntry, Flashcard } from '../components/widgets/decks'

export const NORM_GLOSSARY: GlossaryEntry[] = [
  {
    "term": {
      "en": "Vector norm (axioms)",
      "hu": "Vektornorma (axiómák)"
    },
    "def": {
      "en": "$\\|\\cdot\\|\\colon\\mathbb{R}^n\\to\\mathbb{R}$ with (1) $\\|\\mathbf{x}\\|\\ge0$, $=0$ iff $\\mathbf{x}=\\mathbf{0}$; (2) $\\|c\\mathbf{x}\\|=|c|\\,\\|\\mathbf{x}\\|$; (3) triangle inequality $\\|\\mathbf{x}+\\mathbf{y}\\|\\le\\|\\mathbf{x}\\|+\\|\\mathbf{y}\\|$.",
      "hu": "$\\|\\cdot\\|\\colon\\mathbb{R}^n\\to\\mathbb{R}$, melyre (1) $\\|\\mathbf{x}\\|\\ge0$, $=0$ pontosan ha $\\mathbf{x}=\\mathbf{0}$; (2) $\\|c\\mathbf{x}\\|=|c|\\,\\|\\mathbf{x}\\|$; (3) háromszög-egyenlőtlenség $\\|\\mathbf{x}+\\mathbf{y}\\|\\le\\|\\mathbf{x}\\|+\\|\\mathbf{y}\\|$."
    }
  },
  {
    "term": {
      "en": "$p$-norms (1, 2, ∞)",
      "hu": "$p$-normák (1, 2, ∞)"
    },
    "def": {
      "en": "$\\|\\mathbf{x}\\|_p=(\\sum_i|x_i|^p)^{1/p}$. Special cases: $\\|\\mathbf{x}\\|_1=\\sum_i|x_i|$, the Euclidean $\\|\\mathbf{x}\\|_2$, and $\\|\\mathbf{x}\\|_\\infty=\\max_i|x_i|$.",
      "hu": "$\\|\\mathbf{x}\\|_p=(\\sum_i|x_i|^p)^{1/p}$. Speciális esetek: $\\|\\mathbf{x}\\|_1=\\sum_i|x_i|$, az euklideszi $\\|\\mathbf{x}\\|_2$, és $\\|\\mathbf{x}\\|_\\infty=\\max_i|x_i|$."
    }
  },
  {
    "term": {
      "en": "Reverse triangle inequality (Thm 2.41)",
      "hu": "Fordított háromszög-egyenlőtlenség (2.41. tétel)"
    },
    "def": {
      "en": "$\\big|\\,\\|\\mathbf{x}\\|-\\|\\mathbf{y}\\|\\,\\big|\\le\\|\\mathbf{x}-\\mathbf{y}\\|$ for any norm; it implies every norm is a continuous function on $\\mathbb{R}^n$.",
      "hu": "$\\big|\\,\\|\\mathbf{x}\\|-\\|\\mathbf{y}\\|\\,\\big|\\le\\|\\mathbf{x}-\\mathbf{y}\\|$ bármely normára; ebből következik, hogy minden norma folytonos függvény $\\mathbb{R}^n$-en."
    }
  },
  {
    "term": {
      "en": "Cauchy–Schwarz inequality (Thm 2.42 / 2.43)",
      "hu": "Cauchy–Schwarz-egyenlőtlenség (2.42 / 2.43)"
    },
    "def": {
      "en": "$|\\mathbf{x}^T\\mathbf{y}|\\le\\|\\mathbf{x}\\|_2\\|\\mathbf{y}\\|_2$, with equality iff $\\mathbf{y}=\\lambda\\mathbf{x}$. Proved via the nonnegative quadratic $p(t)=\\sum(tx_i-y_i)^2$; it gives the Euclidean triangle inequality.",
      "hu": "$|\\mathbf{x}^T\\mathbf{y}|\\le\\|\\mathbf{x}\\|_2\\|\\mathbf{y}\\|_2$, egyenlőség pontosan ha $\\mathbf{y}=\\lambda\\mathbf{x}$. A nemnegatív $p(t)=\\sum(tx_i-y_i)^2$ kvadratikus polinommal bizonyítható; ebből jön az euklideszi háromszög-egyenlőtlenség."
    }
  },
  {
    "term": {
      "en": "Norm equivalence & convergence (Thm 2.44/2.45)",
      "hu": "Normaekvivalencia és konvergencia (2.44/2.45)"
    },
    "def": {
      "en": "$\\mathbf{p}^{(k)}\\to\\mathbf{p}$ means $\\|\\mathbf{p}^{(k)}-\\mathbf{p}\\|\\to0$. On $\\mathbb{R}^n$ all norms are equivalent ($m\\|\\cdot\\|_1\\le\\|\\cdot\\|\\le M\\|\\cdot\\|_1$), so convergence is norm-independent and equals componentwise convergence.",
      "hu": "$\\mathbf{p}^{(k)}\\to\\mathbf{p}$ azt jelenti, $\\|\\mathbf{p}^{(k)}-\\mathbf{p}\\|\\to0$. $\\mathbb{R}^n$-en minden norma ekvivalens ($m\\|\\cdot\\|_1\\le\\|\\cdot\\|\\le M\\|\\cdot\\|_1$), így a konvergencia normától független, és megegyezik a komponensenkénti konvergenciával."
    }
  },
  {
    "term": {
      "en": "Induced (operator) matrix norm",
      "hu": "Indukált (operátor) mátrixnorma"
    },
    "def": {
      "en": "$\\|\\mathbf{A}\\|=\\sup_{\\mathbf{x}\\ne\\mathbf{0}}\\dfrac{\\|\\mathbf{A}\\mathbf{x}\\|}{\\|\\mathbf{x}\\|}=\\max_{\\|\\mathbf{y}\\|=1}\\|\\mathbf{A}\\mathbf{y}\\|$ — the largest stretch $\\mathbf{A}$ applies, generated by a chosen vector norm.",
      "hu": "$\\|\\mathbf{A}\\|=\\sup_{\\mathbf{x}\\ne\\mathbf{0}}\\dfrac{\\|\\mathbf{A}\\mathbf{x}\\|}{\\|\\mathbf{x}\\|}=\\max_{\\|\\mathbf{y}\\|=1}\\|\\mathbf{A}\\mathbf{y}\\|$ — a legnagyobb nyújtás, amit $\\mathbf{A}$ végez, egy választott vektornorma generálja."
    }
  },
  {
    "term": {
      "en": "Submultiplicativity (Thm 2.46)",
      "hu": "Szubmultiplikativitás (2.46. tétel)"
    },
    "def": {
      "en": "Induced norms satisfy $\\|\\mathbf{A}\\mathbf{x}\\|\\le\\|\\mathbf{A}\\|\\,\\|\\mathbf{x}\\|$ and $\\|\\mathbf{A}\\mathbf{B}\\|\\le\\|\\mathbf{A}\\|\\,\\|\\mathbf{B}\\|$, in addition to the three norm axioms.",
      "hu": "Az indukált normák kielégítik $\\|\\mathbf{A}\\mathbf{x}\\|\\le\\|\\mathbf{A}\\|\\,\\|\\mathbf{x}\\|$-t és $\\|\\mathbf{A}\\mathbf{B}\\|\\le\\|\\mathbf{A}\\|\\,\\|\\mathbf{B}\\|$-t, a három norma-axióma mellett."
    }
  },
  {
    "term": {
      "en": "Column-sum & row-sum formulas (Thm 2.48)",
      "hu": "Oszlop- és sorösszeg-képletek (2.48. tétel)"
    },
    "def": {
      "en": "$\\|\\mathbf{A}\\|_1=\\max_j\\sum_i|a_{ij}|$ (max absolute **column** sum) and $\\|\\mathbf{A}\\|_\\infty=\\max_i\\sum_j|a_{ij}|$ (max absolute **row** sum). The practical way to compute these matrix norms.",
      "hu": "$\\|\\mathbf{A}\\|_1=\\max_j\\sum_i|a_{ij}|$ (legnagyobb abszolút **oszlop**összeg) és $\\|\\mathbf{A}\\|_\\infty=\\max_i\\sum_j|a_{ij}|$ (legnagyobb abszolút **sor**összeg). Így számoljuk ki ezeket a mátrixnormákat."
    }
  },
  {
    "term": {
      "en": "Cauchy criterion & convergence algebra (Thm 2.49)",
      "hu": "Cauchy-kritérium és konvergencia-algebra (2.49. tétel)"
    },
    "def": {
      "en": "Limits are unique; $\\to$ respects linear combinations, scalar sequences and $\\mathbf{A}\\mathbf{p}^{(k)}\\to\\mathbf{A}\\mathbf{p}$. A sequence converges iff it is Cauchy: $\\|\\mathbf{p}^{(k)}-\\mathbf{p}^{(m)}\\|\\to0$.",
      "hu": "A határérték egyértelmű; a $\\to$ tiszteletben tartja a lineáris kombinációkat, skalársorozatokat és $\\mathbf{A}\\mathbf{p}^{(k)}\\to\\mathbf{A}\\mathbf{p}$-t. Egy sorozat pontosan akkor konvergens, ha Cauchy: $\\|\\mathbf{p}^{(k)}-\\mathbf{p}^{(m)}\\|\\to0$."
    }
  },
  {
    "term": {
      "en": "Vector-valued mean value theorem (Thm 2.50)",
      "hu": "Vektorértékű középértéktétel (2.50. tétel)"
    },
    "def": {
      "en": "On an open convex $E$, $\\|\\mathbf{f}(\\mathbf{x})-\\mathbf{f}(\\mathbf{y})\\|\\le\\max_{t\\in[0,1]}\\|\\mathbf{f}'(\\mathbf{y}+t(\\mathbf{x}-\\mathbf{y}))\\|\\,\\|\\mathbf{x}-\\mathbf{y}\\|$ — the Jacobian norm bounds the change of $\\mathbf{f}$. Key for proving n-D contraction.",
      "hu": "Nyílt konvex $E$-n $\\|\\mathbf{f}(\\mathbf{x})-\\mathbf{f}(\\mathbf{y})\\|\\le\\max_{t\\in[0,1]}\\|\\mathbf{f}'(\\mathbf{y}+t(\\mathbf{x}-\\mathbf{y}))\\|\\,\\|\\mathbf{x}-\\mathbf{y}\\|$ — a Jacobi-norma korlátozza $\\mathbf{f}$ változását. Kulcs az n-D kontrakció bizonyításához."
    }
  }
]

export const NORM_FLASHCARDS: Flashcard[] = [
  {"q":"What are the three fundamental properties that define the absolute value of a real number $x$?","a":"1. $|x| \\ge 0$ (and $|x| = 0 \\iff x = 0$), 2. $|xy| = |x||y|$, 3. $|x + y| \\le |x| + |y|$."},
  {"q":"The property $|x + y| \\le |x| + |y|$ for real numbers is known as the _____.","a":"Triangle inequality"},
  {"q":"Geometrically, what does the absolute value $|x - y|$ represent on the real line?","a":"The distance between the two points $x$ and $y$."},
  {"q":"In vector notation, what is represented by the double bar symbol $\\|x\\|$?","a":"A vector norm."},
  {"q":"What is the primary condition for the norm of a vector to be exactly zero?","a":"The vector must be the zero vector (all coordinates are zero)."},
  {"q":"How is the norm of a scalar product $\\|Cx\\|$ related to the vector norm $\\|x\\|$?","a":"$\\|Cx\\| = |C| \\|x\\|$, where $|C|$ is the absolute value of the scalar."},
  {"q":"State the triangle inequality for two $n$-dimensional vectors $x$ and $y$.","a":"$\\|x + y\\| \\le \\|x\\| + \\|y\\|$."},
  {"q":"Which consequence of the triangle inequality establishes that a vector norm is a continuous function?","a":"$|\\|x\\| - \\|y\\|| \\le \\|x - y\\|$."},
  {"q":"Formula: General $p$-norm of a vector $x$ for $p \\ge 1$.","a":"$\\|x\\|_p = (\\sum_{i=1}^n |x_i|^p)^{1/p}$."},
  {"q":"In the definition of the $p$-norm, what is the required range for the real number $p$ to satisfy the triangle inequality?","a":"$p \\ge 1$."},
  {"q":"What is the common name for the vector norm $\\|x\\|_2$?","a":"The Euclidean norm."},
  {"q":"Formula: The 1-norm of a vector $x$.","a":"$\\|x\\|_1 = \\sum_{i=1}^n |x_i|$."},
  {"q":"Term: Infinity norm (or maximum norm) of a vector $x$.","a":"Definition: The maximum absolute value among the vector's components, denoted $\\|x\\|_\\infty = \\max_i |x_i|$."},
  {"q":"How is the triangle inequality for the vector infinity norm proven for a sum $x+y$?","a":"By showing $|x_i + y_i| \\le |x_i| + |y_i| \\le \\|x\\|_\\infty + \\|y\\|_\\infty$ for every component $i$."},
  {"q":"State the Cauchy-Bunyakovsky-Schwarz inequality for real numbers $x_i$ and $y_i$.","a":"$(\\sum_{i=1}^n x_i y_i)^2 \\le (\\sum_{i=1}^n x_i^2) (\\sum_{i=1}^n y_i^2)$."},
  {"q":"Under what condition does the Cauchy-Bunyakovsky-Schwarz inequality hold as an equality?","a":"When one set of numbers is a constant multiple of the other ($y_i = \\lambda x_i$ for all $i$)."},
  {"q":"State the Cauchy-Bunyakovsky-Schwarz inequality using vector notation for the scalar product and 2-norm.","a":"$|x^T y| \\le \\|x\\|_2 \\|y\\|_2$."},
  {"q":"Which specific inequality is used to prove the triangle inequality for the Euclidean (2-norm)?","a":"The Cauchy-Bunyakovsky-Schwarz inequality."},
  {"q":"Geometrically, what does the 2-norm of a two-dimensional vector represent?","a":"The distance from the point $(x_1, x_2)$ to the origin."},
  {"q":"How is the distance between two $n$-dimensional vectors $x$ and $y$ defined using norms?","a":"As the norm of their difference: $\\|x - y\\|$."},
  {"q":"Definition: Convergence of a vector sequence $P_k$ to a limit $P$.","a":"The sequence converges if $\\lim_{k \\to \\infty} \\|P_k - P\\| = 0$ for a chosen vector norm."},
  {"q":"In $R^n$, how does the choice of vector norm affect the limit of a convergent sequence?","a":"It does not; the limit is independent of the selection of the vector norm."},
  {"q":"A vector sequence $P_k$ converges to $P$ if and only if each _____ of $P_k$ converges to the corresponding component of $P$.","a":"Coordinate (or component)"},
  {"q":"Why is the norm of the difference $\\|P_k - P\\|$ useful in numerical analysis?","a":"It provides a way to check if a generated sequence is 'close enough' to the limit to stop the computation."},
  {"q":"How is a matrix norm generated (induced) by a specific vector norm?","a":"$\\|A\\| = \\sup_{x \\ne 0} \\frac{\\|Ax\\|}{\\|x\\|}$."},
  {"q":"In the definition of an induced matrix norm, why can the supremum be replaced by a maximum for matrices?","a":"Because the maximum is always attained for some non-zero vector $x$ in finite-dimensional spaces."},
  {"q":"What is the equivalent unit-vector definition for an induced matrix norm?","a":"$\\|A\\| = \\sup_{\\|y\\|=1} \\|Ay\\|$."},
  {"q":"State the matrix norm property regarding the product of a matrix $A$ and a vector $x$.","a":"$\\|Ax\\| \\le \\|A\\| \\|x\\|$."},
  {"q":"State the sub-multiplicative property for the norms of two square matrices $A$ and $B$.","a":"$\\|AB\\| \\le \\|A\\| \\|B\\|$."},
  {"q":"What is the specific formula for computing the 1-norm of a matrix $A$?","a":"$\\|A\\|_1 = \\max_j \\sum_{i=1}^n |a_{ij}|$ (the maximum absolute column sum)."},
  {"q":"What is the specific formula for computing the infinity norm of a matrix $A$?","a":"$\\|A\\|_\\infty = \\max_i \\sum_{j=1}^n |a_{ij}|$ (the maximum absolute row sum)."},
  {"q":"Why is the matrix 2-norm considered more difficult to compute than the 1-norm or infinity norm?","a":"It requires computing the eigenvalues of the matrix."},
  {"q":"True or False: If a matrix sequence $A_k$ converges to $A$ in the 1-norm, it must also converge to $A$ in the infinity norm.","a":"True (convergence is independent of the norm selection)."},
  {"q":"How is the limit of a linear combination of vector sequences $C P_k + D Q_k$ determined?","a":"It converges to the linear combination of their individual limits: $CP + DQ$."},
  {"q":"State the Cauchy criterion for the convergence of a vector sequence $P_k$.","a":"For every $\\epsilon > 0$, there exists $k_0$ such that $\\|P_k - P_m\\| < \\epsilon$ for all $k, m > k_0$."},
  {"q":"According to the vector-valued Mean Value Theorem, how is the difference $\\|f(x) - f(y)\\|$ estimated using the Jacobian matrix $J$?","a":"$\\|f(x) - f(y)\\| \\le (\\max_{T \\in [0,1]} \\|J(x + T(y-x))\\|) \\|x - y\\|$."},
  {"q":"In the vector-valued Mean Value Theorem, what type of norm is applied to the Jacobian matrix?","a":"A matrix norm (generated by the vector norm used for $x$ and $y$)."},
  {"q":"What does the 'vertical' summation memory aid refer to in matrix norms?","a":"The 1-norm (maximum absolute column sum)."},
  {"q":"What does the 'horizontal' summation memory aid refer to in matrix norms?","a":"The infinity norm (maximum absolute row sum)."},
  {"q":"Concept: $P$-norm for $p=2$.","a":"$\\|x\\|_2 = \\sqrt{|x_1|^2 + |x_2|^2 + \\dots + |x_n|^2}$."},
  {"q":"If the sequence of coordinates $P_{k,i}$ converges for every $i$, what can be concluded about the vector sequence $P_k$?","a":"The vector sequence $P_k$ converges to a limit vector $P$ formed by those coordinate limits."},
  {"q":"If $\\|A\\|$ is an induced matrix norm, what is the value of $\\|I\\|$, where $I$ is the identity matrix?","a":"1 (since $\\sup \\frac{\\|Ix\\|}{\\|x\\|} = \\sup 1$)."}
]
