// Auto-generated learning aids for '2.10 (Vector and Matrix Norms).
import type { GlossaryEntry, Flashcard } from '../components/widgets/decks'

export const NORM_GLOSSARY: GlossaryEntry[] = [
  {
    "term": {
      "en": "Vector norm (axioms)",
      "hu": "Vektornorma (axiómák)"
    },
    "def": {
      "en": "$\\|\\cdot\\|\\colon\\mathbb{R}^n\\to\\mathbb{R}$ with (1) $\\|\\mathbf{x}\\|\\ge0$, $=0$ iff $\\mathbf{x}=\\mathbf{0}$; (2) $\\|c\\mathbf{x}\\|=|c|\\,\\|\\mathbf{x}\\|$; (3) triangle inequality $\\|\\mathbf{x}+\\mathbf{y}\\|\\le\\|\\mathbf{x}\\|+\\|\\mathbf{y}\\|$.",
      "hu": "$\\|\\cdot\\|\\colon\\mathbb{R}^n\\to\\mathbb{R}$, melyre (1) $\\|\\mathbf{x}\\|\\ge0$, $=0$ pontosan ha $\\mathbf{x}=\\mathbf{0}$; (2) $\\|c\\mathbf{x}\\|=|c|\\,\\|\\mathbf{x}\\|$; (3) háromszög-egyenlőtlenség $\\|\\mathbf{x}+\\mathbf{y}\\|\\le\\|\\mathbf{x}\\|+\\|\\mathbf{y}\\|$."
    }
  },
  {
    "term": {
      "en": "$p$-norms (1, 2, ∞)",
      "hu": "$p$-normák (1, 2, ∞)"
    },
    "def": {
      "en": "$\\|\\mathbf{x}\\|_p=(\\sum_i|x_i|^p)^{1/p}$. Special cases: $\\|\\mathbf{x}\\|_1=\\sum_i|x_i|$, the Euclidean $\\|\\mathbf{x}\\|_2$, and $\\|\\mathbf{x}\\|_\\infty=\\max_i|x_i|$.",
      "hu": "$\\|\\mathbf{x}\\|_p=(\\sum_i|x_i|^p)^{1/p}$. Speciális esetek: $\\|\\mathbf{x}\\|_1=\\sum_i|x_i|$, az euklideszi $\\|\\mathbf{x}\\|_2$, és $\\|\\mathbf{x}\\|_\\infty=\\max_i|x_i|$."
    }
  },
  {
    "term": {
      "en": "Reverse triangle inequality (Thm 2.41)",
      "hu": "Fordított háromszög-egyenlőtlenség (2.41. tétel)"
    },
    "def": {
      "en": "$\\big|\\,\\|\\mathbf{x}\\|-\\|\\mathbf{y}\\|\\,\\big|\\le\\|\\mathbf{x}-\\mathbf{y}\\|$ for any norm; it implies every norm is a continuous function on $\\mathbb{R}^n$.",
      "hu": "$\\big|\\,\\|\\mathbf{x}\\|-\\|\\mathbf{y}\\|\\,\\big|\\le\\|\\mathbf{x}-\\mathbf{y}\\|$ bármely normára; ebből következik, hogy minden norma folytonos függvény $\\mathbb{R}^n$-en."
    }
  },
  {
    "term": {
      "en": "Cauchy–Schwarz inequality (Thm 2.42 / 2.43)",
      "hu": "Cauchy–Schwarz-egyenlőtlenség (2.42 / 2.43)"
    },
    "def": {
      "en": "$|\\mathbf{x}^T\\mathbf{y}|\\le\\|\\mathbf{x}\\|_2\\|\\mathbf{y}\\|_2$, with equality iff $\\mathbf{y}=\\lambda\\mathbf{x}$. Proved via the nonnegative quadratic $p(t)=\\sum(tx_i-y_i)^2$; it gives the Euclidean triangle inequality.",
      "hu": "$|\\mathbf{x}^T\\mathbf{y}|\\le\\|\\mathbf{x}\\|_2\\|\\mathbf{y}\\|_2$, egyenlőség pontosan ha $\\mathbf{y}=\\lambda\\mathbf{x}$. A nemnegatív $p(t)=\\sum(tx_i-y_i)^2$ kvadratikus polinommal bizonyítható; ebből jön az euklideszi háromszög-egyenlőtlenség."
    }
  },
  {
    "term": {
      "en": "Norm equivalence & convergence (Thm 2.44/2.45)",
      "hu": "Normaekvivalencia és konvergencia (2.44/2.45)"
    },
    "def": {
      "en": "$\\mathbf{p}^{(k)}\\to\\mathbf{p}$ means $\\|\\mathbf{p}^{(k)}-\\mathbf{p}\\|\\to0$. On $\\mathbb{R}^n$ all norms are equivalent ($m\\|\\cdot\\|_1\\le\\|\\cdot\\|\\le M\\|\\cdot\\|_1$), so convergence is norm-independent and equals componentwise convergence.",
      "hu": "$\\mathbf{p}^{(k)}\\to\\mathbf{p}$ azt jelenti, $\\|\\mathbf{p}^{(k)}-\\mathbf{p}\\|\\to0$. $\\mathbb{R}^n$-en minden norma ekvivalens ($m\\|\\cdot\\|_1\\le\\|\\cdot\\|\\le M\\|\\cdot\\|_1$), így a konvergencia normától független, és megegyezik a komponensenkénti konvergenciával."
    }
  },
  {
    "term": {
      "en": "Induced (operator) matrix norm",
      "hu": "Indukált (operátor) mátrixnorma"
    },
    "def": {
      "en": "$\\|\\mathbf{A}\\|=\\sup_{\\mathbf{x}\\ne\\mathbf{0}}\\dfrac{\\|\\mathbf{A}\\mathbf{x}\\|}{\\|\\mathbf{x}\\|}=\\max_{\\|\\mathbf{y}\\|=1}\\|\\mathbf{A}\\mathbf{y}\\|$ — the largest stretch $\\mathbf{A}$ applies, generated by a chosen vector norm.",
      "hu": "$\\|\\mathbf{A}\\|=\\sup_{\\mathbf{x}\\ne\\mathbf{0}}\\dfrac{\\|\\mathbf{A}\\mathbf{x}\\|}{\\|\\mathbf{x}\\|}=\\max_{\\|\\mathbf{y}\\|=1}\\|\\mathbf{A}\\mathbf{y}\\|$ — a legnagyobb nyújtás, amit $\\mathbf{A}$ végez, egy választott vektornorma generálja."
    }
  },
  {
    "term": {
      "en": "Submultiplicativity (Thm 2.46)",
      "hu": "Szubmultiplikativitás (2.46. tétel)"
    },
    "def": {
      "en": "Induced norms satisfy $\\|\\mathbf{A}\\mathbf{x}\\|\\le\\|\\mathbf{A}\\|\\,\\|\\mathbf{x}\\|$ and $\\|\\mathbf{A}\\mathbf{B}\\|\\le\\|\\mathbf{A}\\|\\,\\|\\mathbf{B}\\|$, in addition to the three norm axioms.",
      "hu": "Az indukált normák kielégítik $\\|\\mathbf{A}\\mathbf{x}\\|\\le\\|\\mathbf{A}\\|\\,\\|\\mathbf{x}\\|$-t és $\\|\\mathbf{A}\\mathbf{B}\\|\\le\\|\\mathbf{A}\\|\\,\\|\\mathbf{B}\\|$-t, a három norma-axióma mellett."
    }
  },
  {
    "term": {
      "en": "Column-sum & row-sum formulas (Thm 2.48)",
      "hu": "Oszlop- és sorösszeg-képletek (2.48. tétel)"
    },
    "def": {
      "en": "$\\|\\mathbf{A}\\|_1=\\max_j\\sum_i|a_{ij}|$ (max absolute **column** sum) and $\\|\\mathbf{A}\\|_\\infty=\\max_i\\sum_j|a_{ij}|$ (max absolute **row** sum). The practical way to compute these matrix norms.",
      "hu": "$\\|\\mathbf{A}\\|_1=\\max_j\\sum_i|a_{ij}|$ (legnagyobb abszolút **oszlop**összeg) és $\\|\\mathbf{A}\\|_\\infty=\\max_i\\sum_j|a_{ij}|$ (legnagyobb abszolút **sor**összeg). Így számoljuk ki ezeket a mátrixnormákat."
    }
  },
  {
    "term": {
      "en": "Cauchy criterion & convergence algebra (Thm 2.49)",
      "hu": "Cauchy-kritérium és konvergencia-algebra (2.49. tétel)"
    },
    "def": {
      "en": "Limits are unique; $\\to$ respects linear combinations, scalar sequences and $\\mathbf{A}\\mathbf{p}^{(k)}\\to\\mathbf{A}\\mathbf{p}$. A sequence converges iff it is Cauchy: $\\|\\mathbf{p}^{(k)}-\\mathbf{p}^{(m)}\\|\\to0$.",
      "hu": "A határérték egyértelmű; a $\\to$ tiszteletben tartja a lineáris kombinációkat, skalársorozatokat és $\\mathbf{A}\\mathbf{p}^{(k)}\\to\\mathbf{A}\\mathbf{p}$-t. Egy sorozat pontosan akkor konvergens, ha Cauchy: $\\|\\mathbf{p}^{(k)}-\\mathbf{p}^{(m)}\\|\\to0$."
    }
  },
  {
    "term": {
      "en": "Vector-valued mean value theorem (Thm 2.50)",
      "hu": "Vektorértékű középértéktétel (2.50. tétel)"
    },
    "def": {
      "en": "On an open convex $E$, $\\|\\mathbf{f}(\\mathbf{x})-\\mathbf{f}(\\mathbf{y})\\|\\le\\max_{t\\in[0,1]}\\|\\mathbf{f}'(\\mathbf{y}+t(\\mathbf{x}-\\mathbf{y}))\\|\\,\\|\\mathbf{x}-\\mathbf{y}\\|$ — the Jacobian norm bounds the change of $\\mathbf{f}$. Key for proving n-D contraction.",
      "hu": "Nyílt konvex $E$-n $\\|\\mathbf{f}(\\mathbf{x})-\\mathbf{f}(\\mathbf{y})\\|\\le\\max_{t\\in[0,1]}\\|\\mathbf{f}'(\\mathbf{y}+t(\\mathbf{x}-\\mathbf{y}))\\|\\,\\|\\mathbf{x}-\\mathbf{y}\\|$ — a Jacobi-norma korlátozza $\\mathbf{f}$ változását. Kulcs az n-D kontrakció bizonyításához."
    }
  }
]

export const NORM_FLASHCARDS: Flashcard[] = [
  {"q":{"en":"What are the three fundamental properties that define the absolute value of a real number $x$?","hu":"Mi az a három alapvető tulajdonság, amely egy $x$ valós szám abszolút értékét definiálja?"},"a":{"en":"1. $|x| \\ge 0$ (and $|x| = 0 \\iff x = 0$), 2. $|xy| = |x||y|$, 3. $|x + y| \\le |x| + |y|$.","hu":"1. $|x| \\ge 0$ (és $|x| = 0 \\iff x = 0$), 2. $|xy| = |x||y|$, 3. $|x + y| \\le |x| + |y|$."}},
  {"q":{"en":"The property $|x + y| \\le |x| + |y|$ for real numbers is known as the _____.","hu":"Az $|x + y| \\le |x| + |y|$ tulajdonság valós számokra _____ néven ismert."},"a":{"en":"Triangle inequality","hu":"Háromszög-egyenlőtlenség"}},
  {"q":{"en":"Geometrically, what does the absolute value $|x - y|$ represent on the real line?","hu":"Geometriailag mit jelent az $|x - y|$ abszolút érték a számegyenesen?"},"a":{"en":"The distance between the two points $x$ and $y$.","hu":"Az $x$ és $y$ pontok közötti távolságot."}},
  {"q":{"en":"In vector notation, what is represented by the double bar symbol $\\|x\\|$?","hu":"Vektorjelölésben mit jelöl a dupla vonalas $\\|x\\|$ szimbólum?"},"a":{"en":"A vector norm.","hu":"Egy vektornormát."}},
  {"q":{"en":"What is the primary condition for the norm of a vector to be exactly zero?","hu":"Mi az alapfeltétele annak, hogy egy vektor normája pontosan nulla legyen?"},"a":{"en":"The vector must be the zero vector (all coordinates are zero).","hu":"A vektornak a nullvektornak kell lennie (minden koordinátája nulla)."}},
  {"q":{"en":"How is the norm of a scalar product $\\|Cx\\|$ related to the vector norm $\\|x\\|$?","hu":"Hogyan viszonyul a skalárszorzat normája $\\|Cx\\|$ a vektornormához $\\|x\\|$?"},"a":{"en":"$\\|Cx\\| = |C| \\|x\\|$, where $|C|$ is the absolute value of the scalar.","hu":"$\\|Cx\\| = |C| \\|x\\|$, ahol $|C|$ a skalár abszolút értéke."}},
  {"q":{"en":"State the triangle inequality for two $n$-dimensional vectors $x$ and $y$.","hu":"Mondd ki a háromszög-egyenlőtlenséget két $n$-dimenziós $x$ és $y$ vektorra."},"a":{"en":"$\\|x + y\\| \\le \\|x\\| + \\|y\\|$.","hu":"$\\|x + y\\| \\le \\|x\\| + \\|y\\|$."}},
  {"q":{"en":"Which consequence of the triangle inequality establishes that a vector norm is a continuous function?","hu":"A háromszög-egyenlőtlenség melyik következménye mutatja, hogy a vektornorma folytonos függvény?"},"a":{"en":"$|\\|x\\| - \\|y\\|| \\le \\|x - y\\|$.","hu":"$|\\|x\\| - \\|y\\|| \\le \\|x - y\\|$."}},
  {"q":{"en":"Formula: General $p$-norm of a vector $x$ for $p \\ge 1$.","hu":"Képlet: Egy $x$ vektor általános $p$-normája $p \\ge 1$-re."},"a":{"en":"$\\|x\\|_p = (\\sum_{i=1}^n |x_i|^p)^{1/p}$.","hu":"$\\|x\\|_p = (\\sum_{i=1}^n |x_i|^p)^{1/p}$."}},
  {"q":{"en":"In the definition of the $p$-norm, what is the required range for the real number $p$ to satisfy the triangle inequality?","hu":"A $p$-norma definíciójában mi a $p$ valós szám megkövetelt tartománya a háromszög-egyenlőtlenség teljesüléséhez?"},"a":{"en":"$p \\ge 1$.","hu":"$p \\ge 1$."}},
  {"q":{"en":"What is the common name for the vector norm $\\|x\\|_2$?","hu":"Mi a $\\|x\\|_2$ vektornorma közismert neve?"},"a":{"en":"The Euclidean norm.","hu":"Az euklideszi norma."}},
  {"q":{"en":"Formula: The 1-norm of a vector $x$.","hu":"Képlet: Egy $x$ vektor 1-normája."},"a":{"en":"$\\|x\\|_1 = \\sum_{i=1}^n |x_i|$.","hu":"$\\|x\\|_1 = \\sum_{i=1}^n |x_i|$."}},
  {"q":{"en":"Term: Infinity norm (or maximum norm) of a vector $x$.","hu":"Fogalom: Egy $x$ vektor végtelen (maximum-) normája."},"a":{"en":"Definition: The maximum absolute value among the vector's components, denoted $\\|x\\|_\\infty = \\max_i |x_i|$.","hu":"Definíció: A vektor komponensei közötti maximális abszolút érték, jelölve $\\|x\\|_\\infty = \\max_i |x_i|$."}},
  {"q":{"en":"How is the triangle inequality for the vector infinity norm proven for a sum $x+y$?","hu":"Hogyan bizonyítjuk a vektor végtelen-norma háromszög-egyenlőtlenségét egy $x+y$ összegre?"},"a":{"en":"By showing $|x_i + y_i| \\le |x_i| + |y_i| \\le \\|x\\|_\\infty + \\|y\\|_\\infty$ for every component $i$.","hu":"Megmutatva, hogy $|x_i + y_i| \\le |x_i| + |y_i| \\le \\|x\\|_\\infty + \\|y\\|_\\infty$ minden $i$ komponensre."}},
  {"q":{"en":"State the Cauchy-Bunyakovsky-Schwarz inequality for real numbers $x_i$ and $y_i$.","hu":"Mondd ki a Cauchy–Bunyakovszkij–Schwarz-egyenlőtlenséget az $x_i$ és $y_i$ valós számokra."},"a":{"en":"$(\\sum_{i=1}^n x_i y_i)^2 \\le (\\sum_{i=1}^n x_i^2) (\\sum_{i=1}^n y_i^2)$.","hu":"$(\\sum_{i=1}^n x_i y_i)^2 \\le (\\sum_{i=1}^n x_i^2) (\\sum_{i=1}^n y_i^2)$."}},
  {"q":{"en":"Under what condition does the Cauchy-Bunyakovsky-Schwarz inequality hold as an equality?","hu":"Milyen feltétel mellett teljesül egyenlőségként a Cauchy–Bunyakovszkij–Schwarz-egyenlőtlenség?"},"a":{"en":"When one set of numbers is a constant multiple of the other ($y_i = \\lambda x_i$ for all $i$).","hu":"Amikor az egyik számsorozat a másik konstansszorosa ($y_i = \\lambda x_i$ minden $i$-re)."}},
  {"q":{"en":"State the Cauchy-Bunyakovsky-Schwarz inequality using vector notation for the scalar product and 2-norm.","hu":"Mondd ki a Cauchy–Bunyakovszkij–Schwarz-egyenlőtlenséget vektorjelöléssel a skalárszorzatra és a 2-normára."},"a":{"en":"$|x^T y| \\le \\|x\\|_2 \\|y\\|_2$.","hu":"$|x^T y| \\le \\|x\\|_2 \\|y\\|_2$."}},
  {"q":{"en":"Which specific inequality is used to prove the triangle inequality for the Euclidean (2-norm)?","hu":"Melyik konkrét egyenlőtlenséget használjuk az euklideszi (2-) norma háromszög-egyenlőtlenségének bizonyítására?"},"a":{"en":"The Cauchy-Bunyakovsky-Schwarz inequality.","hu":"A Cauchy–Bunyakovszkij–Schwarz-egyenlőtlenséget."}},
  {"q":{"en":"Geometrically, what does the 2-norm of a two-dimensional vector represent?","hu":"Geometriailag mit jelent egy kétdimenziós vektor 2-normája?"},"a":{"en":"The distance from the point $(x_1, x_2)$ to the origin.","hu":"Az $(x_1, x_2)$ pont origótól mért távolságát."}},
  {"q":{"en":"How is the distance between two $n$-dimensional vectors $x$ and $y$ defined using norms?","hu":"Hogyan definiáljuk normák segítségével két $n$-dimenziós $x$ és $y$ vektor távolságát?"},"a":{"en":"As the norm of their difference: $\\|x - y\\|$.","hu":"A különbségük normájaként: $\\|x - y\\|$."}},
  {"q":{"en":"Definition: Convergence of a vector sequence $P_k$ to a limit $P$.","hu":"Definíció: Egy $P_k$ vektorsorozat konvergenciája egy $P$ határértékhez."},"a":{"en":"The sequence converges if $\\lim_{k \\to \\infty} \\|P_k - P\\| = 0$ for a chosen vector norm.","hu":"A sorozat konvergál, ha $\\lim_{k \\to \\infty} \\|P_k - P\\| = 0$ egy választott vektornormára."}},
  {"q":{"en":"In $R^n$, how does the choice of vector norm affect the limit of a convergent sequence?","hu":"$R^n$-ben hogyan befolyásolja a vektornorma választása egy konvergens sorozat határértékét?"},"a":{"en":"It does not; the limit is independent of the selection of the vector norm.","hu":"Sehogy; a határérték független a vektornorma megválasztásától."}},
  {"q":{"en":"A vector sequence $P_k$ converges to $P$ if and only if each _____ of $P_k$ converges to the corresponding component of $P$.","hu":"Egy $P_k$ vektorsorozat akkor és csak akkor konvergál $P$-hez, ha $P_k$ minden _____ a $P$ megfelelő komponenséhez konvergál."},"a":{"en":"Coordinate (or component)","hu":"Koordinátája (komponense)"}},
  {"q":{"en":"Why is the norm of the difference $\\|P_k - P\\|$ useful in numerical analysis?","hu":"Miért hasznos a $\\|P_k - P\\|$ különbség normája a numerikus analízisben?"},"a":{"en":"It provides a way to check if a generated sequence is 'close enough' to the limit to stop the computation.","hu":"Módot ad annak ellenőrzésére, hogy egy előállított sorozat „elég közel” van-e a határértékhez a számítás leállításához."}},
  {"q":{"en":"How is a matrix norm generated (induced) by a specific vector norm?","hu":"Hogyan generál (indukál) egy adott vektornorma egy mátrixnormát?"},"a":{"en":"$\\|A\\| = \\sup_{x \\ne 0} \\frac{\\|Ax\\|}{\\|x\\|}$.","hu":"$\\|A\\| = \\sup_{x \\ne 0} \\frac{\\|Ax\\|}{\\|x\\|}$."}},
  {"q":{"en":"In the definition of an induced matrix norm, why can the supremum be replaced by a maximum for matrices?","hu":"Egy indukált mátrixnorma definíciójában miért cserélhető a szuprémum maximumra mátrixoknál?"},"a":{"en":"Because the maximum is always attained for some non-zero vector $x$ in finite-dimensional spaces.","hu":"Mert véges dimenziós terekben a maximumot mindig felveszi valamilyen nem nulla $x$ vektor."}},
  {"q":{"en":"What is the equivalent unit-vector definition for an induced matrix norm?","hu":"Mi az indukált mátrixnorma egységvektorral megadott ekvivalens definíciója?"},"a":{"en":"$\\|A\\| = \\sup_{\\|y\\|=1} \\|Ay\\|$.","hu":"$\\|A\\| = \\sup_{\\|y\\|=1} \\|Ay\\|$."}},
  {"q":{"en":"State the matrix norm property regarding the product of a matrix $A$ and a vector $x$.","hu":"Mondd ki a mátrixnorma tulajdonságát egy $A$ mátrix és egy $x$ vektor szorzatára."},"a":{"en":"$\\|Ax\\| \\le \\|A\\| \\|x\\|$.","hu":"$\\|Ax\\| \\le \\|A\\| \\|x\\|$."}},
  {"q":{"en":"State the sub-multiplicative property for the norms of two square matrices $A$ and $B$.","hu":"Mondd ki a szubmultiplikatív tulajdonságot két $A$ és $B$ négyzetes mátrix normájára."},"a":{"en":"$\\|AB\\| \\le \\|A\\| \\|B\\|$.","hu":"$\\|AB\\| \\le \\|A\\| \\|B\\|$."}},
  {"q":{"en":"What is the specific formula for computing the 1-norm of a matrix $A$?","hu":"Mi az $A$ mátrix 1-normájának kiszámítási képlete?"},"a":{"en":"$\\|A\\|_1 = \\max_j \\sum_{i=1}^n |a_{ij}|$ (the maximum absolute column sum).","hu":"$\\|A\\|_1 = \\max_j \\sum_{i=1}^n |a_{ij}|$ (a maximális abszolút oszlopösszeg)."}},
  {"q":{"en":"What is the specific formula for computing the infinity norm of a matrix $A$?","hu":"Mi az $A$ mátrix végtelen-normájának kiszámítási képlete?"},"a":{"en":"$\\|A\\|_\\infty = \\max_i \\sum_{j=1}^n |a_{ij}|$ (the maximum absolute row sum).","hu":"$\\|A\\|_\\infty = \\max_i \\sum_{j=1}^n |a_{ij}|$ (a maximális abszolút sorösszeg)."}},
  {"q":{"en":"Why is the matrix 2-norm considered more difficult to compute than the 1-norm or infinity norm?","hu":"Miért nehezebb kiszámítani a mátrix 2-normáját az 1-normánál vagy a végtelen-normánál?"},"a":{"en":"It requires computing the eigenvalues of the matrix.","hu":"A mátrix sajátértékeinek kiszámítását igényli."}},
  {"q":{"en":"True or False: If a matrix sequence $A_k$ converges to $A$ in the 1-norm, it must also converge to $A$ in the infinity norm.","hu":"Igaz vagy hamis: Ha egy $A_k$ mátrixsorozat 1-normában $A$-hoz konvergál, akkor végtelen-normában is $A$-hoz konvergál."},"a":{"en":"True (convergence is independent of the norm selection).","hu":"Igaz (a konvergencia független a norma megválasztásától)."}},
  {"q":{"en":"How is the limit of a linear combination of vector sequences $C P_k + D Q_k$ determined?","hu":"Hogyan határozzuk meg a vektorsorozatok $C P_k + D Q_k$ lineáris kombinációjának határértékét?"},"a":{"en":"It converges to the linear combination of their individual limits: $CP + DQ$.","hu":"Az egyedi határértékeik lineáris kombinációjához konvergál: $CP + DQ$."}},
  {"q":{"en":"State the Cauchy criterion for the convergence of a vector sequence $P_k$.","hu":"Mondd ki a Cauchy-kritériumot egy $P_k$ vektorsorozat konvergenciájára."},"a":{"en":"For every $\\epsilon > 0$, there exists $k_0$ such that $\\|P_k - P_m\\| < \\epsilon$ for all $k, m > k_0$.","hu":"Minden $\\epsilon > 0$-ra létezik $k_0$, hogy $\\|P_k - P_m\\| < \\epsilon$ minden $k, m > k_0$-ra."}},
  {"q":{"en":"According to the vector-valued Mean Value Theorem, how is the difference $\\|f(x) - f(y)\\|$ estimated using the Jacobian matrix $J$?","hu":"A vektorértékű középértéktétel szerint hogyan becsüljük a $\\|f(x) - f(y)\\|$ különbséget a $J$ Jacobi-mátrix segítségével?"},"a":{"en":"$\\|f(x) - f(y)\\| \\le (\\max_{T \\in [0,1]} \\|J(x + T(y-x))\\|) \\|x - y\\|$.","hu":"$\\|f(x) - f(y)\\| \\le (\\max_{T \\in [0,1]} \\|J(x + T(y-x))\\|) \\|x - y\\|$."}},
  {"q":{"en":"In the vector-valued Mean Value Theorem, what type of norm is applied to the Jacobian matrix?","hu":"A vektorértékű középértéktételben milyen típusú normát alkalmazunk a Jacobi-mátrixra?"},"a":{"en":"A matrix norm (generated by the vector norm used for $x$ and $y$).","hu":"Egy mátrixnormát (amelyet az $x$ és $y$-ra használt vektornorma generál)."}},
  {"q":{"en":"What does the 'vertical' summation memory aid refer to in matrix norms?","hu":"Mire utal a „függőleges” összegzés memóriasegédlet a mátrixnormákban?"},"a":{"en":"The 1-norm (maximum absolute column sum).","hu":"Az 1-normára (maximális abszolút oszlopösszeg)."}},
  {"q":{"en":"What does the 'horizontal' summation memory aid refer to in matrix norms?","hu":"Mire utal a „vízszintes” összegzés memóriasegédlet a mátrixnormákban?"},"a":{"en":"The infinity norm (maximum absolute row sum).","hu":"A végtelen-normára (maximális abszolút sorösszeg)."}},
  {"q":{"en":"Concept: $P$-norm for $p=2$.","hu":"Fogalom: $P$-norma $p=2$-re."},"a":{"en":"$\\|x\\|_2 = \\sqrt{|x_1|^2 + |x_2|^2 + \\dots + |x_n|^2}$.","hu":"$\\|x\\|_2 = \\sqrt{|x_1|^2 + |x_2|^2 + \\dots + |x_n|^2}$."}},
  {"q":{"en":"If the sequence of coordinates $P_{k,i}$ converges for every $i$, what can be concluded about the vector sequence $P_k$?","hu":"Ha a $P_{k,i}$ koordinátasorozat minden $i$-re konvergál, mit következtethetünk a $P_k$ vektorsorozatról?"},"a":{"en":"The vector sequence $P_k$ converges to a limit vector $P$ formed by those coordinate limits.","hu":"A $P_k$ vektorsorozat egy $P$ határvektorhoz konvergál, amelyet ezek a koordináta-határértékek alkotnak."}},
  {"q":{"en":"If $\\|A\\|$ is an induced matrix norm, what is the value of $\\|I\\|$, where $I$ is the identity matrix?","hu":"Ha $\\|A\\|$ indukált mátrixnorma, mennyi $\\|I\\|$ értéke, ahol $I$ az egységmátrix?"},"a":{"en":"1 (since $\\sup \\frac{\\|Ix\\|}{\\|x\\|} = \\sup 1$).","hu":"1 (mivel $\\sup \\frac{\\|Ix\\|}{\\|x\\|} = \\sup 1$)."}}
]
