import type { QuizQuestion } from '../components/Quiz';
import type { ModuleId } from '../context/ProgressContext';

export const quizzesHu: Record<ModuleId, QuizQuestion[]> = {
  'fixed-point': [
    {
      id: 'fp1',
      prompt: 'Az xₖ₊₁ = T xₖ + c iteráció pontosan akkor konvergál minden kezdeti értékre, ha:',
      options: ['‖T‖∞ < 1', 'ρ(T) < 1', 'det(T) = 0', 'T szimmetrikus'],
      answer: 1,
      explanation: 'A minden x⁽⁰⁾-ra való konvergencia ekvivalens azzal, hogy ρ(T) < 1.',
    },
    {
      id: 'fp2',
      prompt: 'Az I + A + A² + ⋯ Neumann-sor a (I − A)⁻¹-hez konvergál, ha:',
      options: ['ρ(A) < 1', 'ρ(A) > 1', 'A invertálható', 'Csak ha A = 0'],
      answer: 0,
      explanation: 'A geometriai sor mátrix-megfelelője, ρ(A) < 1 esetén érvényes.',
    },
    {
      id: 'fp3',
      prompt: 'A ‖x − xₖ‖ ≤ ‖T‖ᵏ‖x − x₀‖ becslés szerint a kisebb ‖T‖:',
      tex: '\\|x - x^{(k)}\\| \\le \\|T\\|^k\\,\\|x - x^{(0)}\\|',
      options: ['Lassabb konvergencia', 'Gyorsabb konvergencia', 'Nincs hatása', 'Divergencia'],
      answer: 1,
      explanation: 'A hibát minden lépésben ‖T‖-vel szorozzuk, így a kisebb érték gyorsabban csökkenti.',
    },
    {
      id: 'fp4',
      prompt: 'Ha ρ(T) = 1.4, akkor a fixpont iteráció általában:',
      options: ['Konvergál', 'Divergál', 'Korlátosan örökké oszcillál', 'Csak néha konvergál'],
      answer: 1,
      explanation: 'ρ(T) ≥ 1 sérti a konvergencia-feltételt, így az iteráltak általában elszállnak.',
    },
  ],
  'jacobi-gs': [
    {
      id: 'jg1',
      prompt: 'Melyik módszer használja fel azonnal a frissen kiszámolt komponenseket ugyanazon menetben?',
      options: ['Jacobi', 'Gauss–Seidel', 'Mindkettő', 'Egyik sem'],
      answer: 1,
      explanation: 'A Gauss–Seidel xⱼ^(k+1)-et használ j < i-re; a Jacobi csak a régi x^(k) értékeket.',
    },
    {
      id: 'jg2',
      prompt: 'Egy elegendő feltétel, amely mindkét módszer konvergenciáját garantálja, hogy A:',
      options: ['Szinguláris', 'Diagonálisan domináns', 'Felső háromszög', 'Ferdén szimmetrikus'],
      answer: 1,
      explanation: 'A diagonális dominanciából ‖T_J‖∞ < 1 következik, ami garantálja a konvergenciát.',
    },
    {
      id: 'jg3',
      prompt: 'A Jacobi-iterációs mátrix:',
      tex: '\\mathbf{T}_J = -\\mathbf{D}^{-1}(\\mathbf{L}+\\mathbf{U})',
      options: ['−(D+L)⁻¹U', '−D⁻¹(L+U)', 'D⁻¹(L+U)', '(I−A)⁻¹'],
      answer: 1,
      explanation: 'A Jacobi az A = L + D + U felbontásnál csak a D átlót invertálja.',
    },
    {
      id: 'jg4',
      prompt: 'A diagonálisan domináns tankönyvi rendszernél a Gauss–Seidel a Jacobihoz képest jellemzően:',
      options: [
        'Kevesebb lépésben konvergál',
        'Több lépésben konvergál',
        'Sosem konvergál',
        'Más megoldást ad',
      ],
      answer: 0,
      explanation: 'A frissített értékek felhasználása itt gyorsabbá teszi (kb. 12 vs. 18 lépés).',
    },
  ],
  spectral: [
    {
      id: 'sp1',
      prompt: 'Geometriailag ρ(T) < 1 azt jelenti, hogy T minden sajátértéke:',
      options: [
        'A valós tengelyen van',
        'Az egységkörön belül van',
        'Az egységkörön kívül van',
        'Az origóban van',
      ],
      answer: 1,
      explanation: 'ρ(T) a max |λ|; ρ(T) < 1 ⇔ minden sajátérték szigorúan az egységkörön belül.',
    },
    {
      id: 'sp2',
      prompt: 'Bármely mátrixnormára a spektrálsugár:',
      tex: '\\rho(\\mathbf{T}) \\;?\\; \\|\\mathbf{T}\\|',
      options: ['ρ(T) ≥ ‖T‖', 'ρ(T) ≤ ‖T‖', 'ρ(T) = ‖T‖ mindig', 'Nincs összefüggés'],
      answer: 1,
      explanation: 'ρ(T) ≤ ‖T‖ minden mátrixnormára.',
    },
    {
      id: 'sp3',
      prompt: 'Ha ‖T‖∞ = 1.2, de ρ(T) = 0.7, akkor az iteráció:',
      options: ['Biztosan divergál', 'Konvergál (csak a normateszt bukik)', 'Nem eldönthető', 'Nem értelmezett'],
      answer: 1,
      explanation: 'A normateszt csak elegendő; ρ(T) < 1 már garantálja a konvergenciát.',
    },
    {
      id: 'sp4',
      prompt: 'A ‖T‖∞ kiszámítása:',
      options: [
        'A legnagyobb abszolút sorösszeg',
        'A legnagyobb abszolút oszlopösszeg',
        'A legnagyobb sajátérték',
        'Az összes elem összege',
      ],
      answer: 0,
      explanation: 'A ‖·‖∞ a legnagyobb abszolút sorösszeg (a ‖·‖₁ az oszlopösszeges változat).',
    },
  ],
  condition: [
    {
      id: 'co1',
      prompt: 'A kondíciószám definíciója:',
      tex: '\\operatorname{cond}(\\mathbf{A}) = \\|\\mathbf{A}\\|\\,\\|\\mathbf{A}^{-1}\\|',
      options: ['‖A‖ + ‖A⁻¹‖', '‖A‖ · ‖A⁻¹‖', '‖A‖ / ‖A⁻¹‖', 'det(A)'],
      answer: 1,
      explanation: 'cond(A) = ‖A‖·‖A⁻¹‖ a választott normára nézve.',
    },
    {
      id: 'co2',
      prompt: 'A kis reziduum ‖b − A x̃‖ csak akkor garantál kis hibát, ha:',
      options: [
        'cond(A) kicsi',
        'cond(A) nagy',
        'A szinguláris',
        'b = 0',
      ],
      answer: 0,
      explanation: 'A hibakorlát cond(A)-val skálázódik; rossz kondíció esetén a kis reziduum nagy hibát rejthet.',
    },
    {
      id: 'co3',
      prompt: 'n növelésével a Hilbert-mátrix Hₙ kondíciószáma:',
      options: ['1 közelében marad', 'Rendkívül gyorsan nő', 'Csökken', 'Oszcillál'],
      answer: 1,
      explanation: 'cond₂(Hₙ) nagyjából exponenciálisan nő — Hₙ a klasszikus rosszul kondícionált példa.',
    },
    {
      id: 'co4',
      prompt: 'Ha b-t δ relatív mértékben perturbáljuk, x legfeljebb ennyit változik:',
      tex: '\\frac{\\|\\Delta x\\|}{\\|x\\|} \\le \\operatorname{cond}(\\mathbf{A})\\,\\delta',
      options: ['δ', 'cond(A) · δ', 'δ / cond(A)', 'δ²'],
      answer: 1,
      explanation: 'A relatív hibát legfeljebb a kondíciószám erősíti fel.',
    },
  ],
};
