[package]
name = "rust_app_cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "REPL for the matrix language"

[[bin]]
name = "rmath"
path = "src/main.rs"

[dependencies]
engine.workspace = true
numerics.workspace = true
rustyline = "14"
