// Help entries for the Mapping Toolbox, extracted from mapping.ts.
// Keyed by function name; consumed via ToolboxModule.help (see tb/types.ts).
import type { HelpEntry } from '../help';

export const HELP_MAPPING: Record<string, HelpEntry | string> = {
    km2rad: { summary: 'Convert distance from kilometers to radians', syntax: ['rad = km2rad(km)', 'rad = km2rad(km,radius)'], seealso: ['rad2km', 'deg2km'] },
    rad2km: { summary: 'Convert distance from radians to kilometers', syntax: ['km = rad2km(rad)', 'km = rad2km(rad,radius)'], seealso: ['km2rad', 'deg2km'] },
    deg2km: { summary: 'Convert distance from degrees to kilometers', syntax: ['km = deg2km(deg)'], seealso: ['km2deg', 'deg2nm', 'deg2rad'] },
    km2deg: { summary: 'Convert distance from kilometers to degrees', syntax: ['deg = km2deg(km)'], seealso: ['deg2km', 'km2rad'] },
    deg2nm: { summary: 'Convert distance from degrees to nautical miles', syntax: ['nm = deg2nm(deg)'], seealso: ['nm2deg', 'deg2km'] },
    nm2km: { summary: 'Convert distance from nautical miles to kilometers', syntax: ['km = nm2km(nm)'], seealso: ['km2nm', 'nm2deg'] },
    km2nm: { summary: 'Convert distance from kilometers to nautical miles', syntax: ['nm = km2nm(km)'], seealso: ['nm2km', 'km2sm'] },
    nm2sm: { summary: 'Convert distance from nautical to statute miles', syntax: ['sm = nm2sm(nm)'], seealso: ['sm2nm', 'nm2deg'] },
    sm2nm: { summary: 'Convert distance from statute to nautical miles', syntax: ['nm = sm2nm(sm)'], seealso: ['nm2sm', 'sm2km'] },
    km2sm: { summary: 'Convert distance from kilometers to statute miles', syntax: ['sm = km2sm(km)', 'sm = km2sm(km,radius)'], description: ['sm = km2sm(km) converts a distance from kilometers to statute miles using Earth\'s mean radius.'], seealso: ['sm2km', 'km2nm'] },
    sm2km: { summary: 'Convert distance from statute miles to kilometers', syntax: ['km = sm2km(sm)'], seealso: ['km2sm', 'sm2nm'] },
    deg2sm: { summary: 'Convert distance from degrees to statute miles', syntax: ['sm = deg2sm(deg)'], seealso: ['sm2deg', 'deg2km'] },
    sm2deg: { summary: 'Convert distance from statute miles to degrees', syntax: ['deg = sm2deg(sm)'], seealso: ['deg2sm', 'sm2km'] },
    nm2deg: { summary: 'Convert distance from nautical miles to degrees', syntax: ['deg = nm2deg(nm)', 'deg = nm2deg(nm,radius)'], description: ['deg = nm2deg(nm) converts a distance in nautical miles to degrees of arc along a great circle using Earth\'s mean radius.'], seealso: ['deg2nm', 'nm2km'] },
    rad2nm: { summary: 'Convert distance from radians to nautical miles', syntax: ['nm = rad2nm(rad)'], seealso: ['nm2rad', 'rad2km'] },
    nm2rad: { summary: 'Convert distance from nautical miles to radians', syntax: ['rad = nm2rad(nm)'], seealso: ['rad2nm', 'nm2deg'] },
    rad2sm: { summary: 'Convert distance from radians to statute miles', syntax: ['sm = rad2sm(rad)'], seealso: ['sm2rad', 'rad2km'] },
    sm2rad: { summary: 'Convert distance from statute miles to radians', syntax: ['rad = sm2rad(sm)'], seealso: ['rad2sm', 'sm2km'] },
    meanm: { summary: 'Mean location of geographic coordinates', syntax: ['[latm,lonm] = meanm(lat,lon)'], seealso: ['distance', 'azimuth'] },
    changem: { summary: 'Substitute values in array', syntax: ['B = changem(A,newval,oldval)'], seealso: ['ismember'] },
    ingeoquad: { summary: 'True for points inside or on lat-lon quadrangle', syntax: ['tf = ingeoquad(lat,lon,latlim,lonlim)'], seealso: ['inpolygon'] },
    ecef2enuv: { summary: 'Rotate ECEF vector to local ENU', syntax: ['[uE,vN,wU] = ecef2enuv(U,V,W,lat0,lon0)'], seealso: ['enu2ecefv', 'ecef2enu'] },
    enu2ecefv: { summary: 'Rotate local ENU vector to ECEF', syntax: ['[U,V,W] = enu2ecefv(uE,vN,wU,lat0,lon0)'], seealso: ['ecef2enuv', 'enu2ecef'] },
    ecef2nedv: { summary: 'Rotate ECEF vector to local NED', syntax: ['[uN,vE,wD] = ecef2nedv(U,V,W,lat0,lon0)'], seealso: ['ned2ecefv', 'ecef2ned'] },
    ned2ecefv: { summary: 'Rotate local NED vector to ECEF', syntax: ['[U,V,W] = ned2ecefv(uN,vE,wD,lat0,lon0)'], seealso: ['ecef2nedv', 'ned2ecef'] },
    toDegrees: { summary: 'Convert angles to degrees', syntax: ['deg = toDegrees(angleUnits,angles)'], description: ["deg = toDegrees('radians',angles) converts angles from any angular unit ('radians', 'degrees') to degrees."], seealso: ['fromDegrees', 'deg2rad'] },
    fromDegrees: { summary: 'Convert angles from degrees', syntax: ['angles = fromDegrees(angleUnits,deg)'], description: ["angles = fromDegrees('radians',deg) converts angles in degrees to the specified angular unit."], seealso: ['toDegrees', 'deg2rad'] },
    distance: { summary: 'Angular or surface distance between two geographic points', syntax: ['d = distance(pt1,pt2)', 'd = distance(lat1,lon1,lat2,lon2)'], seealso: ['azimuth', 'reckon', 'departure'] },
    azimuth: { summary: 'Azimuth between two geographic points', syntax: ['az = azimuth(lat1,lon1,lat2,lon2)', 'az = azimuth(pt1,pt2)'], description: ['az = azimuth(lat1,lon1,lat2,lon2) returns the azimuth angle (clockwise from north, in degrees) from point 1 to point 2 on a sphere.', 'The function uses the great circle (geodesic) path.'], seealso: ['distance', 'reckon', 'departure'] },
    reckon: { summary: 'Point at a given azimuth and range from a starting location', syntax: ['[latout,lonout] = reckon(lat,lon,rng,az)'], seealso: ['distance', 'azimuth'] },
    departure: { summary: 'Longitude distance (departure) between two meridians at given latitudes', syntax: ['d = departure(lon1,lon2,lat)'], description: ['d = departure(lon1,lon2,lat) returns the east-west distance (in degrees of arc) between meridians lon1 and lon2 at latitude lat.'], seealso: ['distance', 'azimuth'] },
    antipode: { summary: 'Point diametrically opposite on the globe', syntax: ['[latout,lonout] = antipode(lat,lon)'], seealso: ['distance', 'azimuth'] },
    wrapTo180: { summary: 'Wrap angle in degrees to [-180, 180]', syntax: ['lon = wrapTo180(lon)'], description: ['lon = wrapTo180(lon) wraps angles in degrees to the interval [-180, 180] such that -180 maps to -180 and 180 maps to 180.'], seealso: ['wrapTo360', 'wrapToPi'] },
    wrapTo360: { summary: 'Wrap angle in degrees to [0, 360]', syntax: ['lon = wrapTo360(lon)'], seealso: ['wrapTo180', 'wrapToPi'] },
    wrapToPi: { summary: 'Wrap angle in radians to [-pi, pi]', syntax: ['lon = wrapToPi(lon)'], description: ['lon = wrapToPi(lon) wraps angles in radians to the interval [-pi, pi], analogous to wrapTo180 for degrees.'], seealso: ['wrapTo2Pi', 'wrapTo180'] },
    wrapTo2Pi: { summary: 'Wrap angle in radians to [0, 2*pi]', syntax: ['lon = wrapTo2Pi(lon)'], seealso: ['wrapToPi', 'wrapTo360'] },
    wgs84Ellipsoid: { summary: 'WGS84 reference ellipsoid parameters [semimajor, eccentricity]', syntax: ['e = wgs84Ellipsoid'], seealso: ['earthRadius', 'flat2ecc'] },
    earthRadius: { summary: 'Mean radius of planet Earth', syntax: ['r = earthRadius', "r = earthRadius(units)"], description: ["r = earthRadius returns Earth's mean radius in meters (6371000 m).", "r = earthRadius('km') returns it in kilometers; supported units include 'meters', 'km', 'nm', 'miles'."], seealso: ['wgs84Ellipsoid', 'flat2ecc'] },
    ecc2flat: { summary: 'Flattening of an ellipse from eccentricity', syntax: ['f = ecc2flat(ecc)'], seealso: ['flat2ecc', 'ecc2n'] },
    flat2ecc: { summary: 'Eccentricity of an ellipse from flattening', syntax: ['ecc = flat2ecc(f)'], description: ['ecc = flat2ecc(f) returns the eccentricity e of an ellipse with flattening f, using e = sqrt(2f - f^2).'], seealso: ['ecc2flat', 'n2ecc'] },
    ecc2n: { summary: 'Third flattening from eccentricity', syntax: ['n = ecc2n(ecc)'], seealso: ['n2ecc', 'ecc2flat'] },
    n2ecc: { summary: 'Eccentricity from third flattening', syntax: ['ecc = n2ecc(n)'], description: ['ecc = n2ecc(n) returns the eccentricity of an ellipse with third flattening n = (a-b)/(a+b).'], seealso: ['ecc2n', 'flat2ecc'] },
    majaxis: { summary: 'Semimajor axis from semiminor axis and eccentricity', syntax: ['a = majaxis(b,ecc)'], seealso: ['minaxis', 'flat2ecc'] },
    minaxis: { summary: 'Semiminor axis from semimajor axis and eccentricity', syntax: ['b = minaxis(a,ecc)'], description: ['b = minaxis(a,ecc) returns the semiminor axis b = a*sqrt(1-ecc^2) of an ellipse.'], seealso: ['majaxis', 'ecc2flat'] },
    geocentricLatitude: { summary: 'Convert geodetic to geocentric latitude', syntax: ['latc = geocentricLatitude(latd,ecc)'], seealso: ['parametricLatitude', 'geodetic2ecef'] },
    parametricLatitude: { summary: 'Convert geodetic to parametric (reduced) latitude', syntax: ['latp = parametricLatitude(latd,ecc)'], description: ['latp = parametricLatitude(latd,ecc) returns the parametric (reduced) latitude corresponding to geodetic latitude latd for an ellipse with eccentricity ecc.'], seealso: ['geocentricLatitude', 'geodetic2ecef'] },
    meridianarc: { summary: 'Ellipsoidal distance along a meridian', syntax: ['d = meridianarc(phi1,phi2,ecc)'], seealso: ['distance', 'earthRadius'] },
    geodetic2ecef: { summary: 'Transform geodetic to ECEF coordinates', syntax: ['[X,Y,Z] = geodetic2ecef(lat,lon,h)'], description: ['[X,Y,Z] = geodetic2ecef(lat,lon,h) converts geodetic coordinates (latitude lat in degrees, longitude lon in degrees, height h in meters) to Earth-centered Earth-fixed (ECEF) Cartesian coordinates.'], seealso: ['ecef2geodetic', 'ecef2enu', 'enu2ecef'] },
    ecef2geodetic: { summary: 'Transform ECEF to geodetic coordinates', syntax: ['[lat,lon,h] = ecef2geodetic(X,Y,Z)'], description: ['[lat,lon,h] = ecef2geodetic(X,Y,Z) converts ECEF Cartesian coordinates to geodetic latitude (degrees), longitude (degrees), and height (meters).'], seealso: ['geodetic2ecef', 'ecef2enu'] },
    ecef2enu: { summary: 'Transform ECEF to local east-north-up coordinates', syntax: ['[E,N,U] = ecef2enu(X,Y,Z,lat0,lon0,h0)'], description: ['[E,N,U] = ecef2enu(X,Y,Z,lat0,lon0,h0) transforms ECEF coordinates to a local ENU frame centered at the reference geodetic point (lat0,lon0,h0).'], seealso: ['enu2ecef', 'ecef2ned', 'geodetic2enu'] },
    enu2ecef: { summary: 'Transform local east-north-up to ECEF coordinates', syntax: ['[X,Y,Z] = enu2ecef(E,N,U,lat0,lon0,h0)'], description: ['[X,Y,Z] = enu2ecef(E,N,U,lat0,lon0,h0) converts ENU local coordinates to ECEF, given the reference geodetic origin.'], seealso: ['ecef2enu', 'ned2ecef', 'enu2geodetic'] },
    ecef2ned: { summary: 'Transform ECEF to local north-east-down coordinates', syntax: ['[N,E,D] = ecef2ned(X,Y,Z,lat0,lon0,h0)'], seealso: ['ned2ecef', 'ecef2enu'] },
    ned2ecef: { summary: 'Transform local north-east-down to ECEF coordinates', syntax: ['[X,Y,Z] = ned2ecef(N,E,D,lat0,lon0,h0)'], seealso: ['ecef2ned', 'enu2ecef'] },
    geodetic2enu: { summary: 'Transform geodetic to local east-north-up', syntax: ['[E,N,U] = geodetic2enu(lat,lon,h,lat0,lon0,h0)'], seealso: ['enu2geodetic', 'geodetic2ecef'] },
    enu2geodetic: { summary: 'Transform local east-north-up to geodetic', syntax: ['[lat,lon,h] = enu2geodetic(E,N,U,lat0,lon0,h0)'], seealso: ['geodetic2enu', 'ecef2geodetic'] },
    geodetic2ned: { summary: 'Transform geodetic to local north-east-down', syntax: ['[N,E,D] = geodetic2ned(lat,lon,h,lat0,lon0,h0)'], seealso: ['ned2geodetic', 'geodetic2enu'] },
    ned2geodetic: { summary: 'Transform local north-east-down to geodetic', syntax: ['[lat,lon,h] = ned2geodetic(N,E,D,lat0,lon0,h0)'], seealso: ['geodetic2ned', 'ecef2geodetic'] },
    aer2enu: { summary: 'Transform azimuth-elevation-range to east-north-up', syntax: ['[E,N,U] = aer2enu(az,elev,slantRange)'], seealso: ['enu2aer', 'aer2ned'] },
    enu2aer: { summary: 'Transform east-north-up to azimuth-elevation-range', syntax: ['[az,elev,slantRange] = enu2aer(E,N,U)'], seealso: ['aer2enu', 'ned2aer'] },
    aer2ned: { summary: 'Transform azimuth-elevation-range to north-east-down', syntax: ['[N,E,D] = aer2ned(az,elev,slantRange)'], seealso: ['ned2aer', 'aer2enu'] },
    ned2aer: { summary: 'Transform north-east-down to azimuth-elevation-range', syntax: ['[az,elev,slantRange] = ned2aer(N,E,D)'], seealso: ['aer2ned', 'enu2aer'] },
    geodetic2aer: { summary: 'Transform geodetic to local azimuth-elevation-range', syntax: ['[az,elev,slantRange] = geodetic2aer(lat,lon,h,lat0,lon0,h0)'], seealso: ['aer2geodetic', 'geodetic2enu'] },
    aer2geodetic: { summary: 'Transform azimuth-elevation-range to geodetic', syntax: ['[lat,lon,h] = aer2geodetic(az,elev,slantRange,lat0,lon0,h0)'], seealso: ['geodetic2aer', 'ecef2geodetic'] },
    ecef2aer: { summary: 'Transform ECEF to local azimuth-elevation-range', syntax: ['[az,elev,slantRange] = ecef2aer(X,Y,Z,lat0,lon0,h0)'], seealso: ['aer2ecef', 'ecef2enu'] },
    aer2ecef: { summary: 'Transform azimuth-elevation-range to ECEF', syntax: ['[X,Y,Z] = aer2ecef(az,elev,slantRange,lat0,lon0,h0)'], seealso: ['ecef2aer', 'enu2ecef'] },
    degrees2dms: { summary: 'Convert decimal degrees to degrees-minutes-seconds', syntax: ['dms = degrees2dms(deg)'], seealso: ['dms2degrees', 'degrees2dm'] },
    degrees2dm: { summary: 'Convert decimal degrees to degrees-minutes', syntax: ['dm = degrees2dm(deg)'], seealso: ['dm2degrees', 'degrees2dms'] },
    dms2degrees: { summary: 'Convert degrees-minutes-seconds to decimal degrees', syntax: ['deg = dms2degrees(dms)'], seealso: ['degrees2dms', 'dm2degrees'] },
    dm2degrees: { summary: 'Convert degrees-minutes to decimal degrees', syntax: ['deg = dm2degrees(dm)'], seealso: ['degrees2dm', 'dms2degrees'] },
    interpm: { summary: 'Densify latitude-longitude sampling in lines or polygons', syntax: ['[lati,loni] = interpm(lat,lon,maxdiff)'], seealso: ['distance', 'azimuth'] },
    angl2str: { summary: 'Format angle as a string', syntax: ["str = angl2str(ang)", "str = angl2str(ang,'format',units)"], seealso: ['degrees2dms', 'num2str'] },
  };
